- common/config/azure-pipelines/templates/build-publish.yaml
@aruniverse I think this should fix the issue.  It's how we handle some of our other internal repos.
The `rush publish` command in this case will handle both pushing the version bump to the repo and publishing the packages.
> Remove the explicit version bump, rely on the 'rush publish' to publish and commit

- common/changes/@bentley/tree-widget-react/zachz-modelTreeClearfix_2020-07-09-14-48.json
- packages/tree-widget/src/components/search-bar/SearchBar.tsx
- packages/tree-widget/src/components/search-bar/SearchBox.scss
- packages/tree-widget/src/components/search-bar/SearchBox.tsx
Fix for bug: Model Tree Search - Clear doesn't remove search
description + repro steps:
Clicking the 'X' on the search does not remove the search criteria.
Steps:
Open Model Tree
Click search box
enter search criteria - tree filters as expected
Click the 'X' in the search box to clear the search
Result - the search box closes but the filter is still applied to the tree
User most close and reopen the model tree to see the full tree.
The 'X' should clear the search filter.
> Clear text in search box when the close button is clicked

- common/config/azure-pipelines/templates/build-publish.yaml
The `--include-all` flag help docs read "will be published if their version is newer than published version" which makes it seem like it will only publish if the bump has happened prior to this step.
I ran it locally without "--publish", which actually stops it from committing the changes, but everything seemed to have worked in terms of using the changelogs to apply the version bump and then hopefully the publish step.
> Fix publish build by excluding `--include-all` flag to allow bump

- common/changes/@bentley/tree-widget-react/2d3dtoggle_2020-08-10-20-07.json
- packages/tree-widget/README.md
- packages/tree-widget/public/locales/en/TreeWidget.json
- packages/tree-widget/src/components/IconButton.scss
- packages/tree-widget/src/components/IconButton.tsx
- packages/tree-widget/src/components/header/TreeHeader.tsx
- packages/tree-widget/src/components/trees/ModelsTree.tsx
Added icon buttons to tree header for 2D and 3D visibility toggles. This included some logic added to the ModelTree as well as adding a label property to the icon button (to display "2D" and "3D" next to the new buttons).
> Added 2D & 3D Visibility Toggles

- common/changes/@bentley/property-grid-react/favorite-properties-fix_2020-08-26-14-25.json
- packages/property-grid/src/components/PropertyGrid.tsx
Fix property data provider being destroyed on receiving props. Only do it on iModel Connection changes, and if so, maintain enableFavoriteProperties prop.
> Favorite Properties Fix

- common/changes/@bentley/property-grid-react/property-group-nesting_2020-09-29-18-57.json
- packages/property-grid/src/components/PropertyGrid.tsx
PBI: https://dev.azure.com/bentleycs/beconnect/_workitems/edit/444702/
Enabled property group nesting, unless the data provider is passed in through props (in which case we don't want to overwrite what is passed in).
> Enabled property group nesting in property-grid package

- common/changes/@bentley/imodel-content-tree-react/fix-pkg-fields_2020-10-07-16-21.json
- packages/imodel-content-tree/package.json
Without this change consumers of the package are not able to correctly import using the `import { } from "@bentley/imodel-content-tree"`. Fix the name of the main and typings within the package.json to correctly match the barrel file.
> Fix main and typings field in imodel-content-tree package

- common/changes/@bentley/imodel-content-tree-react/imodel-content-tree-handle-GraphicalPartition3ds_2020-10-16-11-36.json
- packages/imodel-content-tree/src/components/Hierarchy.json
Nodes of Models that model PhysicalPartitions are node displayed, if the partition's JsonProperties has 'PhysicalPartition.Model.Content' attribute. Similar behavior should apply to GraphicalPartition3d - it's model should not be displayed if it's JsonProperties has 'GraphicalPartition3d.Model.Content' attribute.
> imodel-content-tree: Handle GraphicalPartition3d similar to PhysicalPartition

- common/changes/@bentley/markup-frontstage-react/bug-fix-view-type-filter_2020-10-15-21-49.json
- packages/markup-frontstage/src/services/SavedView.ts
This PR contains the fix for isSpatialView functionality, because of which 2D view state was delivered instead of 3D view state to the frontstage.
> Bug/fix 3D view filter in isSpatialView function

- common/changes/@bentley/imodel-react-hooks/fix-bad-table-pipes-imodel-hooks-readme_2020-10-28-20-22.json
- packages/imodel-react-hooks/README.md
apparently github's markdown flavor doesn't recognize pipes between backticks as outside of the current table context due to part of the markdown spec they use and its choice on inline contexts.
So had to update the README to fix wrong columns being chosen
> Fix bad table pipes imodel hooks readme

- common/changes/@bentley/property-grid-react/longname-in-properties-panel_2020-12-03-16-08.json
- packages/property-grid/src/components/ElementList.scss
- packages/property-grid/src/components/PropertyGrid.scss
Fix for an issue with long names cutting off in the properties panel. Removed the height restriction for the header div. Tested and it works fine for both short and long names without the hardcoded height.
> Long names cutting off in properties panel

- common/changes/@bentley/tree-widget-react/search-box-fixes_2020-12-09-16-35.json
- packages/tree-widget/src/components/IconButton.tsx
- packages/tree-widget/src/components/search-bar/SearchBox.scss
Search box incorrectly resizes due to the addition of labels.
> Search box fixes

- common/changes/@bentley/tree-widget-react/bug-search-styling_2020-12-14-21-02.json
- packages/tree-widget/src/components/search-bar/SearchBar.scss
in UI 2.0 with resizable widgets, absolute positioning is causing overlap. Also adjusted transition time:
> fix search styling issues

- common/changes/@bentley/imodel-react-hooks/fix-dont-recreate-html-element_2021-01-21-16-39.json
- packages/imodel-react-hooks/src/IModelJsViewProvider.tsx
- packages/imodel-react-hooks/src/Marker/useMarker.ts
patch change
- should allow you to animate correctly since updates don't delete the root element
- should increase performance when using jsxElement
- it should have worked this way from the beginning, can't believe I just noticed
- used viewFilter when invalidating viewports to not invalidate all of them
> patch: don't recreate jsxElement every render

- common/changes/@bentley/imodel-select-react/imodelselect-fix-sass_2021-02-23-20-31.json
- packages/imodel-select/src/components/IModelList.scss
I moved Desktop Starter up to the latest version of Dart Sass and found the following error.  I just added a space and everything seems to be okay :).  Someone with more knowledge of scss can tell me if that was the "correct" solution.
```
SassError: Expected identifier.
╷
39 │     -webkit-transition: color background-color.2s ease;
```
> Fix scss issue found in Dart Sass

- common/changes/@bentley/imodel-content-tree-react/imodel-content-tree-non-geometric-model-content-display-improvements_2021-02-26-06-52.json
- packages/imodel-content-tree/src/components/Hierarchy.json
Changed several things for stuff displayed under non-geometric Models:
- Directly under the Model node show only Elements that have no parent (removes SubCategories that used to appear directly under Model).
- Group those elements by class (identifies the type of node).
- For every Element node load its child Elements as child nodes (puts SubCategories under their parent Category).
> imodel-content-tree: Non-geometric models' content display improvements

- common/changes/@bentley/tree-widget-react/tree-widget-resize_2021-03-23-15-44.json
- packages/tree-widget/src/components/TreeWidgetComponent.scss
Reported by a user in imodeljs git repo: https://github.com/imodeljs/imodeljs/discussions/1005
The tree widget can get into a flickering refresh state when it is resized. I solved this by changing the components-selectable-content class from display: flex to display: block. This seems to keep it out of a endless resize loop when the scroll bars are added.
I tested in docked and undocked states and did not see any problems.
> Tree widget resize

- common/changes/@bentley/tree-widget-react/avoidNestedScrollbars_2021-03-24-17-49.json
- packages/tree-widget/src/components/TreeWidgetComponent.scss
Let the tree provide the only scroll bar and avoid nested scrollbars within widget.
> Avoid nested scrollbars

- common/changes/@bentley/imodel-select-react/bug-imodel-select-react-deps_2021-03-30-23-54.json
- packages/imodel-select/package.json
keeping them as dependencies can cause duplicate versions of react-dom to be loaded, causing multiple errors
> move react and react-dom to peerDependencies

- common/changes/@bentley/imodel-select-react/imodel-select-prevent-infinite-spinner_2021-04-13-14-21.json
- packages/imodel-select/src/components/IModelSelector.tsx
This PR handles getProjects error and resets isLoadingProjects state to prevent rendering the spinner indefinitely.
> Prevent infinite spinner in imodel-select

- common/changes/@bentley/markup-frontstage-react/Disable-view-overlay--solar-timeline-_2021-04-27-21-22.json
- packages/markup-frontstage/src/components/ui/MarkupFrontstageProvider.tsx
For the markup frontstage, always disable the view overlay (solar timeline).
> Disable view overlay (solar timeline)

- common/changes/@bentley/tree-widget-react/Fix--Model-Category-trees-incorrect-height_2021-07-19-16-54.json
- packages/tree-widget/src/components/TreeWidgetComponent.scss
- packages/tree-widget/src/components/trees/ModelsTree.scss
Model & Category were incorrectly sized in the Tree widget.  Since the parent is flexbox, the tree should set flex=1, to size the remaining space.  Also, it was adding unnecessary padding.
> Fix: Model/Category trees incorrect height

- common/config/rush/command-line.json
The rush publish command runs a git commit as a sub-process which triggers the copyright linter git hook. Since it was not marked as safe to run at the same time as other Rush commands, the rush publish and rush copyright:linter were conflicting with each other.
> Allow copyright linter to run at the same time as other steps

- common/config/rush/command-line.json
Somehow in #134 I set this to `false` which is completely useless as that's the default.  Switching it to the appropriate `true` to allow for the parallel processing.
> Turn multi-process support to true this time

- common/changes/@bentley/tree-widget-react/master_2021-11-15-14-50.json
- packages/tree-widget/src/components/trees/ModelsTree.tsx
Fix for an issue where ModelsTree component can lose its state when `selectedView` property spuriously changes to undefined (Happens with `ContentLayoutManager` from `@bentley/ui-framework` and `CivilReviewTools` from `@bentley/civil-reviewtools-frontend`). By "losing the state", I mean, tree nodes in `ControlledTree` reset (for example, expanded/not expanded property).
> Keep component's state when viewport is undefined [ModelsTree]

- common/changes/@bentley/property-grid-react/fix-property-grid-multiselect_2021-12-09-17-48.json
- packages/property-grid/src/components/MultiElementPropertyGrid.tsx
Problem was that the function that figures out if there's multiple elements selected is registered as a listen event, but that event isn't triggered during the initial opening of the widget (i.e. if you select multiple elements which opens the property grid widget, vs having the widget already opened and selecting multiple elements as a new selection). 
Adding a direct call to the onSelectionChange function after registering the event listener ensures it's still called when the widget is first opened.
> Fix: info button not appearing in property grid when selecting multiple elements 

- common/changes/@bentley/tree-widget-react/fixhideallbuttonblocked_2022-01-07-11-55.json
- packages/tree-widget/src/components/search-bar/SearchBar.scss
The search bar was blocking the "Hide All" button when the search bar was closed and you could not click on about 70% of the "Hide All" button from the left side.
> Fix "Hide All" button blocked by search bar

- common/changes/@itwin/grouping-mapping-widget/Fix-for-grouping-mapping-Ui-1.0_2022-02-04-22-07.json
- packages/itwin/grouping-mapping-widget/src/widget/GroupingMappingWidget.tsx
The Grouping Mapping Widget is not working in UI 1.0 contexts because of a defect where it is not checking for the zoneLocation and so does not return the widget to UI 1.0 when provideWidgets is called.
This PR adds a check for AbstractZoneLocation.CenterLeft (4) so that the widget will be returned when called by UiItemsProviders in UI 1.0 contexts.  This does not affect UI 2.0 uses.
> Fix for GroupingMatchingWidget when used in UI 1.0 applications

- common/changes/@itwin/grouping-mapping-widget/group-by-styling-fixes_2022-03-10-01-48.json
- packages/itwin/grouping-mapping-widget/src/widget/components/ActionPanel.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/DeleteModal.scss
- packages/itwin/grouping-mapping-widget/src/widget/components/DeleteModal.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupAction.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupQueryBuilderContext.ts
- packages/itwin/grouping-mapping-widget/src/widget/components/property-grid/PrimitivePropertyRenderer.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/property-grid/PropertyGrid.scss
- packages/itwin/grouping-mapping-widget/src/widget/components/property-grid/PropertyView.scss
- packages/itwin/grouping-mapping-widget/src/widget/components/property-grid/PropertyView.tsx
The property grid had overlapping separator with the labels due to the unexpected checkbox we put in. Fixed it. Too many inline scripted styles made it difficult to do it nicely. Also polished a lot of the loading spinners positioning and added more.
> [Grouping&Mapping] More styling fixes and loading spinners enhancements

- common/changes/@itwin/measure-tools-react/hide-property-grid_2022-03-25-15-27.json
- common/changes/@itwin/property-grid-react/hide-property-grid_2022-03-25-14-51.json
- common/changes/@itwin/property-grid-react/hide-property-grid_2022-03-25-15-41.json
- packages/itwin/measure-tools/src/ui-2.0/MeasurementPropertyWidget.tsx
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/components/FilteringPropertyGrid.tsx
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
- packages/itwin/property-grid/src/types.ts
Hides property grid by default unless at least one non-transient element is in selection set.
> Hide property grid by default

- common/changes/@itwin/tree-widget-react/tree-widget-auto-sizer-fix_2022-04-21-11-58.json
- packages/itwin/tree-widget/src/components/utils/AutoSizer.tsx
Changed AutoSizer behavior to avoid unmounting children when width or height is 0. This was causing trees from `@itwin/appui-react` to lose their state.
> [Tree-Widget] Fix AutoSizer to render children even if width or height is 0

- common/config/azure-pipelines/ci.yaml
If no PR trigger is present in an azure devops pipeline hosted in github, pull request validation is enabled for all branches. By defining the PR trigger ourselves we can override the default behavior. For more info, see [PR triggers in GitHub](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers).
> Add PR trigger to CI pipeline

- common/changes/@itwin/property-grid-react/fix-property-gruid-provider-ui-1.0_2022-05-05-15-05.json
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
The current implementation of the property grid when using a ui items provider is to rely on the useEffect in the MultiElementGrid to handle hiding / showing the property grid on selection events. This won't work in appui v1.0 because the component will be unmounted and cannot have its state changed from that useEffect. 
The workaround is to implement a mechanism similar to what Bill did here: https://github.com/iTwin/itwinjs-core/blob/ce886ecde5caec43972f7b6a4dd4cf3cd13eba06/test-apps/ui-items-providers-test/src/ui/providers/NetworkTracingUiProvider.tsx#L69
If the PropertyGridUiItemsProvider is created in appui v1.0, then a listener will be added (that is cleaned up during the onUnregister callback) that will handle the toggling of the property grid's widget state in place of the …
> [property-grid-react] fix ui items provider so the property grid appears when loaded into appui v1.0

- common/changes/@itwin/tree-widget-react/fix-tree-widget-restore-state_2022-05-05-18-37.json
- packages/itwin/tree-widget/src/components/TreeWidgetUiItemsProvider.tsx
add `restoreTransientState` to the TreeWidgetUiItemsProvider to ensure that the widget's state is restored if remounted such as is the case when used in a tab
> restore transient state of tree widget if remounted (such as when a tab)

- common/changes/@itwin/property-grid-react/fix-property-grid-multi-select-icon_2022-05-06-20-09.json
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
if you select many elements while the property grid is not mounted, it will mount and not show the option to open the multi element property grid because the logic to do so only runs in a selection event handler which will only have been setup after the selection event has fired. The solution is to ensure when the component mounts that logic automatically runs.
> [property-grid-react] ensure the multiselect option appears when component first mounts

- common/changes/@itwin/property-grid-react/fix-property-grid-transient_2022-05-09-17-15.json
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
updates the logic of the onPresentationSelectionChanged handler in the PropertyGridUiItemsProvider, which is meant to handle showing/hiding the property grid when it is set in a tab such as in app ui v1.0, to reflect the logic used in the useEffect in the MultiElementPropertyGrid, which handles showing/hiding the property grid in an app ui v2.0 panel, to prevent showing the property grid when only transient elements (such as view section panes) are selected
> [property-grid-react] don't open property grid tab when only transient elements selected

- common/changes/@itwin/property-grid-react/fix-property-grid-default-zone-location_2022-05-10-16-24.json
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/types.ts
Allow the default zone location (Center.Right) to be overridden by a property grid prop the same way we already support for the panel / section locations (which are used in app ui v2.0 whereas zone location is used only by app ui v1.0)
> [property-grid-react] support overriding the default zone location used in the ui items provider

- common/changes/@itwin/measure-tools-react/bugfix-measure-tools-ui-2.0_2022-05-12-18-47.json
- packages/itwin/measure-tools/src/ui-2.0/MeasurementPropertyWidget.tsx
Fix the MeasurementPropertyWidget (aka MeasurementWidget for ui-2.0) that would not properly expand the measurements while selecting/deselecting them one by one. This is a regression from the older version and is required whenever we use Measurement tools to place multiple measurements. The user should always see the properties of the last created measurement without ever having to expand it manually.
> Bugfix/measure tools UI 2.0

- common/changes/@itwin/property-grid-react/property-grid-auot-expand-child-categories_2022-05-17-20-55.json
- packages/itwin/property-grid/src/api/AutoExpandingPropertyDataProvider.ts
- packages/itwin/property-grid/src/components/FilteringPropertyGrid.tsx
- packages/itwin/property-grid/src/components/PropertyGrid.tsx
- packages/itwin/property-grid/src/types.ts
allow for overriding the child category expansion
default behavior:
if `autoEpandChildCategories` is set to false this will be the result:
> [property-grid-react] support overriding the auto child category expansion behavior

- common/changes/@itwin/property-grid-react/property-grid-force-open-fix_2022-05-18-17-41.json
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
when the property grid is a minimized tab like so:
or merged into a zone with another active like so:
in those cases we do not want to force the property grid to open when a selection event occurs, instead we only want to do this when the property grid is hidden
Note: since this affects only tab behavior it only affects the property grid behavior in app ui v1
> [property-grid-react] if the property grid tab is minimized do not force it open

- common/changes/@itwin/measure-tools-react/bugfix-defaultToolLocalization_2022-05-26-12-22.json
- packages/itwin/measure-tools/src/tools/ClearMeasurementsTool.ts
- packages/itwin/measure-tools/src/tools/MeasureAngleTool.ts
- packages/itwin/measure-tools/src/tools/MeasureAreaTool.ts
- packages/itwin/measure-tools/src/tools/MeasureDistanceTool.ts
- packages/itwin/measure-tools/src/tools/MeasureLocationTool.ts
- packages/itwin/measure-tools/src/tools/MeasurePerpendicularTool.ts
- packages/itwin/measure-tools/src/tools/MeasureRadiusTool.ts
Override the default behavior of obtaining localized strings.
Default implementation resolves to `${toolNamespace}:tools.${toolId}.${localizedStringKey}` which doesn't match the structure of the localized string file of this package.
> [measure-tools] Bugfix/default tool localization

- common/changes/@itwin/property-grid-react/fix-propgrid-specify-position-context-menu_2022-05-25-18-39.json
- packages/itwin/property-grid/src/components/PropertyGrid.tsx
- packages/itwin/property-grid/src/types.ts
Unified Viewer needs the ability to show the additional context menu item for "Share this Favorite" at the top of the dropdown. I added an optional forcePosition property. If set, the item will be added at that position in the list, otherwise it will be added to the end like before.
> [property-grid-react] Added optional forcePosition property to ContextMenuItemInfo

- common/changes/@itwin/grouping-mapping-widget/extractionenabletogglelabel_2022-06-06-11-48.json
- packages/itwin/grouping-mapping-widget/src/widget/components/MappingAction.tsx
Changed the label and it's position for the extraction toggle.
> [Grouping & Mapping] Extraction toggle changes

- .github/CODEOWNERS
- common/changes/@itwin/reports-config-widget-react/rcw-flaky-tests-fix_2022-06-15-17-48.json
- packages/itwin/reports-config-widget/src/test/ReportMappings.test.tsx
- packages/itwin/reports-config-widget/src/test/Reports.test.tsx
faker.random.words(), in rare situations, was using words that the tests would query for. Making them fail.
> [ReportsConfig] Fixed flaky tests

- common/changes/@itwin/property-grid-react/fix-property-grid-frontstage-refresh_2022-06-23-15-15.json
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
- Currently if the  frontstage changes while a selection set is active the property grid will be in an improper state
- This occurs in both UI 1.0 and UI 2.0 but unfortunately a unique solution is required for both
- in UI 1.0 the widget state must be refreshed from an onFrontstageReady listener that is setup from the ui items provider constructor
- in UI 2.0 the state must be refreshed from an additional listener for onFrontstageReady that is setup in a useEffect inside the MultiElementPropertyGrid
- The reason for the difference in solutions is that UI 2.0 the property grid stays mounted so the useEffect listeners can continue syncing its state with ongoing events in the app, while in UI 1.0 it is unmounted and will have to be remounted in the proper state based on these events
> [property-grid-react] refresh property grid when frontstage changes

- common/changes/@itwin/property-grid-react/Property-grid-navigation_2022-07-07-20-19.json
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
Instead of hiding the down navigation button when not available, it was decided to disable the button instead.
Work Item:
https://bentleycs.visualstudio.com/beconnect/_workitems/edit/936785
> Property grid navigation

- common/changes/@itwin/grouping-mapping-widget/query-keywords_2022-07-01-23-01.json
- common/changes/@itwin/grouping-mapping-widget/query-keywords_2022-07-01-23-02.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupAction.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupingMapping.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/context/MappingClientContext.ts
Originally, by default, if no query was being generated by either query generation methods it would take the selected element class and generate a simple query off of that. This made it confusing when generating a query using Query Keywords since it wasn't obvious sometimes which method it was using. The other method was also called Selection, so it'd be better to keep any selection event to that method. 
Also fixed a bug, where no matter the prefix, it would always hit prod first.
> [Grouping&Mapping] query keywords no longer listens to selection and env fix

- common/changes/@itwin/property-grid-react/persist-show-hide-null-per-user_2022-07-22-16-49.json
- packages/itwin/property-grid/src/api/ShowNullValuesPreferenceClient.ts
Removed iTwinId and iModelId from calls to save/get null value toggle so that it is persisted for the user and not as a shared setting.
> Persist the show/hide null values toggle per user instead of per iModel or iTwin.

- .github/CODEOWNERS
@iTwin/itwinjs-core-presentation is taking development ownership of the `tree-widget-react` package.
> Taking ownership of `tree-widget-react`

- common/changes/@itwin/grouping-mapping-widget/Mindaugas-expose-mapping-hooks-ctx_2023-01-13-08-15.json
- common/changes/@itwin/grouping-mapping-widget/Mindaugas-expose-mapping-hooks-ctx_2023-01-13-08-16.json
- packages/itwin/grouping-mapping-widget/src/grouping-mapping-widget.ts
Everything related to `MappingClient` and `GroupingMappingApiConfig` contexts were exposed for better extensibility.
> Exposed contexts, hooks, and types

- common/changes/@itwin/grouping-mapping-widget/group-cleanup_2023-02-24-13-47.json
- packages/itwin/grouping-mapping-widget/src/widget/components/Grouping.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/context/GroupHilitedElementsContext.ts
Removing a redundant callback that was not necessary. useEffect was already making a call to visualizeGroupColorsWrapper.
> Removed redundant callback

- common/changes/@itwin/tree-widget-react/tree-widget-models-tree-remove-unused-filtering-by-element-ids_2023-03-09-13-02.json
- packages/itwin/tree-widget/src/components/trees/models-tree/Hierarchy.GroupedByClass.json
- packages/itwin/tree-widget/src/components/trees/models-tree/Hierarchy.json
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTree.test.tsx
The feature was `@alpha`, was unused and was causing issues with the hierarchy (the underlying issues will be fixed separately)
> Tree Widget: Remove unused feature of filtering the tree by element ids

- common/changes/@itwin/tree-widget-react/tree-widget-restore_hide_all_behavior_2023-03-23-14-30.json
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeComponent.tsx
https://github.com/iTwin/viewer-components-react/commit/0c77c4b965ff9b1211ba636d95ae273f26158b5a changed ShowAll and HideAll buttons behavior to toggle categories visibility alongside models. This works great for ShowAll button but in case of HideAll button it breaks this workflow:
* Open ModelsTree and hide all
* Toggle in the tree Models that you wan to be visible
Previous behavior would enable model and categories would be visible. After https://github.com/iTwin/viewer-components-react/commit/0c77c4b965ff9b1211ba636d95ae273f26158b5a categories are not visible and need to be enabled one by one.
This PR restores HideAll button to previous behavior to only hide models.
> Tree widget: restore hide all button behavior

- common/changes/@itwin/property-grid-react/Make_property_grid_column_resizer_more_movable_2023-04-17-07-15.json
- packages/itwin/property-grid/README.md
- packages/itwin/property-grid/src/components/FilteringPropertyGrid.tsx
- packages/itwin/property-grid/src/components/PropertyGrid.tsx
- packages/itwin/property-grid/src/types.ts
> Make property grid column resizer more movable

- common/changes/@itwin/tree-widget-react/rework_additional_trees_handling_2023-04-14-14-58.json
- common/config/rush/pnpm-lock.yaml
- packages/itwin/tree-widget/.eslintrc.js
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/src/components/TreeWidgetComponent.tsx
- packages/itwin/tree-widget/src/components/TreeWidgetUiItemsProvider.tsx
- packages/itwin/tree-widget/src/components/trees/category-tree/CategoriesTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeComponent.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/377
Refactored `TreeWidgetUiItemsProvider` to have single config property for controlling trees shown in widget instead of having multiple properties hiding/adding trees.
Fixed eslint.
> Tree-Widget: Rework how trees are added to widget

- common/changes/@itwin/map-layers/fix-map-layers-scss_2023-04-18-21-52.json
- packages/itwin/map-layers/src/ui/widget/MapLayerManager.scss
- packages/itwin/map-layers/src/ui/widget/MapUrlDialog.scss
- packages/itwin/map-layers/src/ui/widget/SubLayersTree.scss
Webpack is throwing errors compiling @itwin/map-layers due to the usage of $uicore-button-focus-boxshadow which no longer exists.
I've swapped those references with `rgba(var(--iui-color-border-accent), var(--iui-opacity-4)) 0px 0px 0px 2px;`, which seems to be the easiest replacement given the following:
- In 3.7.x version of appui I found: `$uicore-button-focus-boxshadow: $buic-focus-boxshadow 0px 0px 0px 2px;` and also from there I found `--buic-focus-boxshadow: rgba(var(--iui-color-foreground-primary-rgb), var(--iui-opacity-4));` 
- From the iTwinUI migration [doc](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-variables-v1-migration-guide) I found `--iui-color-foreground-primary-rgb` is now equivalent to `--iui-color-border-accent`
I'm sure there is a simpler replacement, but this …
> Replace removed variable $uicore-button-focus-boxshadow in MapLayer's scss files

- common/changes/@itwin/tree-widget-react/Fix_invert_button_2023-04-18-16-20.json
- common/changes/@itwin/tree-widget-react/conditional_trees_2023-04-24-10-24.json
- common/changes/@itwin/tree-widget-react/jake-breakdown-trees_2023-04-20-20-09.json
- common/changes/@itwin/tree-widget-react/rework_additional_trees_handling_2023-04-14-14-58.json
- common/changes/@itwin/tree-widget-react/tree-widget-models-tree-hierarchy-configuration_2023-05-11-08-05.json
- common/changes/@itwin/tree-widget-react/tree_widget_update_deps_2023-04-21-11-58.json
- common/changes/@itwin/tree-widget-react/update_tree_checkboxes_2023-04-17-16-44.json
Trying to add some consistency for our changelogs... I think the structure to be as follows:
```
{BREAKING CHANGE PREFIX} {Affected  component name}: {Change description}.
```
- `{BREAKING CHANGE PREFIX}` is `**BREAKING**`. Add when the commit contains a breaking change.
- `{Affected  component name}` is one of the harder pieces to come up with. Guidelines:
- It has to be something that consumers understand - it can't be a name of some internal component. In case of a change to internal component, the name should be set to a higher level component that uses the internal one.
- Sometimes the change affects multiple components. In that case:
- When the components are at the same level, consider using a unified name (e.g. "Models tree" + "Categories tree" = "Trees").
- When they're at …
> Tree Widget: Make changelogs consistent

- common/changes/@itwin/tree-widget-react/tree-widget-external-sources-tree_2023-04-07-13-59.json
- common/config/rush/pnpm-lock.yaml
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSources.json
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSourcesTree.tsx
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSourcesTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/index.ts
- packages/itwin/tree-widget/src/test/setup.ts
- packages/itwin/tree-widget/src/test/trees/external-sources-tree/ExternalSourcesTree.test.tsx
- packages/itwin/tree-widget/src/test/trees/external-sources-tree/ExternalSourcesTreeComponent.test.tsx
- packages/itwin/tree-widget/tsconfig.json
This is based on #421 and now targets `tree_widget_1.0`.
Closes https://github.com/iTwin/viewer-components-react/issues/352.
> Tree widget: External sources tree

- common/api/summary/tree-widget-react.exports.csv
- common/api/tree-widget-react.api.md
- packages/itwin/tree-widget/public/locales/en/TreeWidget.json
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSourcesTreeComponent.tsx
- packages/itwin/tree-widget/src/test/trees/external-sources-tree/ExternalSourcesTreeComponent.test.tsx
Fixup https://github.com/iTwin/viewer-components-react/pull/476.
Also, it seems `extract-api` hasn't been with recent changes.
> External sources tree: Add missing attributes `id` and `getLabel`

- common/config/rush/pnpm-lock.yaml
- packages/itwin/tree-widget/.eslintrc.js
- packages/itwin/tree-widget/package.json
Extension of https://github.com/iTwin/viewer-components-react/pull/475. 
Use `eslint-plugin-unused-imports` instead of `@typescript-eslint/no-unused-vars` - it knows how to auto-fix unused type imports.
> Tree widget: Setup linter to cleanup unused type imports

- common/changes/@itwin/property-grid-react/property_grid_cleanup_data_provider_config_2023-05-16-13-49.json
- packages/itwin/property-grid/src/components/PropertyGrid.tsx
- packages/itwin/property-grid/src/components/SingleElementPropertyGrid.tsx
- packages/itwin/property-grid/src/hooks/UseDataProvider.ts
Removed these properties that were used to configure default property data provider:
- `enableFavoriteProperties`
- `enablePropertyGroupNesting`
- `rulesetId`
Instead of these properties `createDataProvider` property should be used to provide customized property data provider.
> Property Widget: Cleanup data provider config

- apps/test-viewer/src/UiProvidersConfig.tsx
- common/changes/@itwin/property-grid-react/property_grid_menu_refactor_2023-05-19-10-58.json
- packages/itwin/property-grid/src/components/PropertyGridContent.tsx
- packages/itwin/property-grid/src/hooks/UseContextMenu.tsx
- packages/itwin/property-grid/src/property-grid-react.ts
Closes https://github.com/iTwin/viewer-components-react/issues/483
Dropped all properties related to context menu configuration in favor of single property `contextMenuItemProviders`. This Provides more flexibility when configuring context menu. Removed properties:
```
enableFavoriteProperties?: boolean;
enableCopyingPropertyText?: boolean;
enableNullValueToggle?: boolean;
additionalContextMenuOptions?: ContextMenuItemInfo[];
defaultContextMenuOptions?: Map<PropertyGridDefaultContextMenuKey, Partial<ContextMenuItemInfo>>;
```
Change `ContextMenuItemInfo` type into `ContextMenuItemDefinition`. It does not extend `ContextMenuItemProps` like `ContextMenuItemInfo` because they were not used anyway.
Some examples of the new API:
In order to add default menu items, there is a list of …
> Property grid: Context menu refactor

- apps/test-viewer/src/UiProvidersConfig.tsx
- common/changes/@itwin/property-grid-react/property_grid_remove_custom_on_data_change_2023-05-19-12-11.json
- packages/itwin/property-grid/src/components/PropertyGridContent.tsx
- packages/itwin/property-grid/src/hooks/UsePropertyGridData.ts
Removed `customOnDataChanged` callback from property grid props. This callback was invoked when `onDataChanged` event was raised. Same behavior can be replicated using `createDataProvider` and `onDataChanged` event:
```typescript
new PropertyGridUiItemsProvider({
propertyGridProps: {
createDataProvider: (imodel) => {
const provider = new PresentationPropertyDataProvider({ imodel });
provider.onDataChanged.addListener(() => { someCallback(); });
return provider;
}
}
})
```
> Property grid: Remove `customOnDataChanged` property

- common/api/summary/tree-widget-react.exports.csv
- common/api/tree-widget-react.api.md
- common/changes/@itwin/tree-widget-react/Keep_eye_checkbox_position_static_on_horizontal_scroll_2023-05-26-11-12.json
- packages/itwin/tree-widget/README.md
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeBase.scss
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeRenderer.tsx
- packages/itwin/tree-widget/src/components/trees/category-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/test/trees/VisibilityTreeRenderer.test.tsx
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTree.test.snap
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTree.test.tsx
> Keep eye checkbox position static on horizontal scroll, make model and categories tree whitespace between eye checkbox and node label smalelr

- apps/test-viewer/src/UiProvidersConfig.tsx
- common/api/property-grid-react.api.md
- common/api/summary/property-grid-react.exports.csv
- common/changes/@itwin/property-grid-react/property_grid_menu_refactor_2023-05-19-10-58.json
- common/changes/@itwin/property-grid-react/property_grid_settings_2023-06-08-08-48.json
- common/changes/@itwin/property-grid-react/property_grid_settings_2023-06-08-08-49.json
- packages/itwin/property-grid/public/locales/en/PropertyGrid.json
- packages/itwin/property-grid/src/components/ElementList.scss
- packages/itwin/property-grid/src/components/ElementList.tsx
- packages/itwin/property-grid/src/components/FilteringPropertyGrid.tsx
- packages/itwin/property-grid/src/components/Header.scss
- packages/itwin/property-grid/src/components/Header.tsx
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.scss
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
- packages/itwin/property-grid/src/components/PropertyGrid.tsx
- packages/itwin/property-grid/src/components/PropertyGridContent.scss
- packages/itwin/property-grid/src/components/PropertyGridContent.tsx
- packages/itwin/property-grid/src/components/SettingsDropdownMenu.tsx
- packages/itwin/property-grid/src/hooks/UseContextMenu.tsx
- packages/itwin/property-grid/src/hooks/UseNullValuesSetting.ts
- packages/itwin/property-grid/src/hooks/UseNullValuesSetting.tsx
- packages/itwin/property-grid/src/property-grid-react.ts
- packages/itwin/property-grid/src/test/components/MultiElementPropertyGrid.test.tsx
- packages/itwin/property-grid/src/test/components/PropertyGridContent.test.tsx
- packages/itwin/property-grid/src/test/components/SettingsDropdownMenu.test.tsx
- packages/itwin/property-grid/src/test/hooks/UseContextMenu.test.tsx
- packages/itwin/property-grid/src/test/hooks/UseNullValuesSetting.test.tsx
- packages/itwin/property-grid/src/test/setup.ts
- packages/itwin/property-grid/tsconfig.json
Closes https://github.com/iTwin/viewer-components-react/issues/499
* Added settings dropdown to header.
* Moved `Show/Hide Empty Values` setting from context menu to settings dropdown.
* Unified PropertyGrid and ElementList headers.
* Cleaned up styles.
Settings dropdown:
> Property grid: Settings dropdown

- common/changes/@itwin/property-grid-react/property_grid_keyboard_navigation_2023-06-14-12-05.json
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/components/Header.tsx
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.scss
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/537
Removed `onKeyDown` handlers from buttons as those were fired when navigating through buttons with TAB.
Made Element List and Property Grid hidden when they are pushed to side. Previously they were always visible but pushed outside of container's visible part. This caused some issues when pressing button to show Element List because focused element was still in Property Grid.
> Property Widget: Improve keyboard navigation

- common/changes/@itwin/grouping-mapping-widget/master_2023-07-11-17-59.json
- packages/itwin/grouping-mapping-widget/src/widget/components/Mapping.tsx
Fixed the bug of Enable/Disable Extraction Button. Now, when you click on 3 dots next to the mapping name and click on Enable/Disable Extraction, it works as intended.
> [G&M] Fixed Enable Extraction Button

- common/api/property-grid-react.api.md
- common/api/summary/property-grid-react.exports.csv
- common/changes/@itwin/property-grid-react/property_grid_ignore_transient_instances_2023-07-14-14-29.json
- packages/itwin/property-grid/src/PropertyGridComponent.tsx
- packages/itwin/property-grid/src/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/hooks/UseInstanceSelection.ts
- packages/itwin/property-grid/src/test/PropertyGridComponent.test.tsx
- packages/itwin/property-grid/src/test/PropertyGridUiItemsProvider.test.tsx
- packages/itwin/property-grid/src/test/hooks/UseInstanceSelection.test.ts
Do not open property grid when transient instance is selected. Also do not add transient instances to selected instances count when multiple instances are selected (some valid and some transient)
> Property grid: Ignore transient instances

- common/changes/@itwin/grouping-mapping-widget/add-arrow_2023-07-12-16-13.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupsAddButton.tsx
Added a dropdown arrow to the Add Group button.
Here is what the button looks like after the change: 
https://github.com/iTwin/viewer-components-react/assets/22688247/15ef63a4-326a-42b4-93f4-280fa7fbb92a
> [G&M] Added a dropdown arrow to the Add Group button.

- common/changes/@itwin/measure-tools-react/fix-measure-tools-unit-changes_2023-07-19-18-19.json
- packages/itwin/measure-tools/src/api/MeasurementManager.ts
Made changes to how the addListeners for unit system changes were being called since it doesn't actually trigger the addListener functions before these changes.
Related bug:
https://bentleycs.visualstudio.com/beconnect/_boards/board/t/Pineapple%20-%20iMVF/Backlog%20items/?workitem=1220088
> [measure-tools] Add listeners for unit system changes in startup

- common/changes/@itwin/measure-tools-react/bugfix-allow-actions-internal-api-usage_2023-07-24-15-54.json
- packages/itwin/measure-tools/package.json
- packages/itwin/measure-tools/src/api/Measurement.ts
- packages/itwin/measure-tools/src/test/measure-tools/Measurement.test.ts
- packages/itwin/measure-tools/src/widgets/MeasurementActionToolbar.tsx
- `allowActions` is now a property getter that can be overridden on `Measurement`. The measurement action toolbar now filters first any measurements who return `false`.
- Investigated cause of non-measurement action items being pulled into the toolbar, filed an [issue](https://github.com/iTwin/appui/issues/424) with AppUi.
- Added lint rule for internal usage APIs and reviewed usage:
- `currentInputState` should not be used and replaced the button event filling with (soon to be) public APIs
- Other internal usage are all soon-to-be promoted APIs
- TODO: ` IModelConnection.requestSnap` will need to be replaced with `AccuSnap.doSnapRequest` when the itwin version is updated
> Added allowActions on Measurement base class. Replaced internal APIs

- common/changes/@itwin/grouping-mapping-widget/custom-calculation-formula-hint_2023-07-18-16-40.json
- packages/itwin/grouping-mapping-widget/src/widget/components/CustomCalculationAction.scss
- packages/itwin/grouping-mapping-widget/src/widget/components/CustomCalculationAction.tsx
Adds an informational icon that the user can hover over to learn about custom calculation formulas. Also adds a placeholder to the formula Textarea with an example formula.
Here is what the UI changes look like:
https://github.com/iTwin/viewer-components-react/assets/22688247/fe658dc4-bcdc-4f76-99a9-cb774afcbc21
> [G&M] Custom calculation formula hint

- common/changes/@itwin/property-grid-react/property-grid-fix-changelog_2023-08-08-06-09.json
- packages/itwin/property-grid/CHANGELOG.json
- packages/itwin/property-grid/CHANGELOG.md
The `CHANGELOG.json` needed update after https://github.com/iTwin/viewer-components-react/issues/601 was fixed.
> Fix `property-grid-react` changelog

- common/changes/@itwin/reports-config-widget-react/uyen-update-dataset-icon_2023-08-14-19-56.json
- packages/itwin/reports-config-widget/src/widget/components/ReportMappingHorizontalTile.tsx
Changed Update Dataset icon from SvgRefresh to SvgPlay to be consistent with the main Report component.
> [Reports Config] Changed Update Dataset icon

- common/changes/@itwin/reports-config-widget-react/uyen-reposition-toolbar-icons_2023-08-14-21-51.json
- packages/itwin/reports-config-widget/src/widget/components/Reports.scss
Moved search and refresh icons to the right side of Report component.
> [Reports Config] Moved toolbar icons to the right

- common/changes/@itwin/reports-config-widget-react/uyen-horizontal-tile-icons_2023-08-14-20-25.json
- packages/itwin/reports-config-widget/src/widget/components/ReportMappingHorizontalTile.tsx
Removed trash icon in horizontal tile when update dataset job is queued
> [Reports Config] Remove trash icon when update job is queued

- common/changes/@itwin/property-grid-react/property_grid_fix_ancestor_detection_2023-08-18-08-51.json
- packages/itwin/property-grid/src/hooks/UseInstanceSelection.ts
- packages/itwin/property-grid/src/test/hooks/UseInstanceSelection.test.ts
Property grid was incorrectly determining if element has parent which resulted in ancestor navigation not working.
> Property grid: Correctly determine if element has parent

- common/changes/@itwin/map-layers/geo-fix_invalidCreds_ui_2023-10-20-15-18.json
- packages/itwin/map-layers/src/ui/widget/MapUrlDialog.tsx
Make sure the credentials warning is correctly displayed after an 'ArcGIS' map-layer (so the first time, but also after an invalid attempt):
This is needed because `@itwin\core-frontend` package doesn't return the appropriate `InvalidCredentials` status after an invalid attempt.
> Fix an issue in the 'Add New Layer' dialog where invalid credentials warning would not appear after a first invalid attempt

- common/changes/@itwin/property-grid-react/property-grid-fix-flaky-test_2023-11-14-14-03.json
- packages/itwin/property-grid/src/test/components/PropertyGridContent.test.tsx
Property filtering test seemed to be flaky on macOS machines. Although the reason for the test failing is unclear, this is an attempt to rewrite the test in a more robust way to reduce the chance of it being flaky.
> Fix flaky test in property-grid

- common/changes/@itwin/map-layers/fix-map-layers-remount_2023-12-18-17-19.json
- packages/itwin/map-layers/src/ui/widget/MapLayersWidget.tsx
- fixes an issue where if the viewport remounts the map layers widget doesn't react correctly because it only updates the isGeolocated either on initial mount or when the `iModel.onEcefLocationChanged` fires
- solution is to run the `updateIsGeoLocated` routine that runs when `iModel.onEcefLocationChanged` fires immediately when the `activeViewport` changes
- see gif to illustrate the problem
> [Map Layers] fix 'No active viewport or geo-located iModel available.' when viewport remounts

- change/@itwin-tree-widget-react-f47044a2-d045-4f8b-b4fa-3baf127320c9.json
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeEventHandler.ts
- packages/itwin/tree-widget/src/components/trees/common/UseVisibilityTreeState.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeEventHandler.tsx
- packages/itwin/tree-widget/src/test/trees/VisibilityTreeEventHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeEventHandler.test.ts
This refactor was needed because having the current implementation in `VisibilityTreeEventHandler` would only work with `ModelsTree`, so creating a new `ModelsTreeEventHandler` which would hold logic that is specific for `ModelsTree` is more correct.
> ModelsTree: move onNodeDoubleClick to ModelsTreeEventHandler

- .pipelines/publish.yaml
- apps/test-viewer/pnpm-lock.yaml
- beachball.config.dev.js
- beachball.config.js
- change/@itwin-tree-widget-react-0c27369e-7f9e-45c9-bdcb-7c87ab609437.json
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeEventHandler.ts
Updated `VisibilityTreeEventHandler.onCheckboxStateChanged` to convert `@itwin/components-react` observable type into `rxjs` observable type. This should prevent possible type errors when multiple `rxjs` versions are present in `node_modules`.
Also updated publish pipeline to support publishing from different branches.
> [Tree widget]: Fix possible `onCheckboxStateChanged` failure when multiple `rxjs` versions are present

- change/@itwin-map-layers-72a70bdf-2393-4315-8a88-420ab9ac81d2.json
- packages/itwin/map-layers/src/ui/FeatureInfoUiItemsProvider.tsx
Incorrectly added tech preview badge with badgeType property instead of badge for the map feature info widget.
> Fix map feature info widget tech preview badge

- change/@itwin-property-grid-react-bf921e2f-5414-4d27-97dc-23fdc3fdec97.json
- change/@itwin-tree-widget-react-da85ee4d-5dda-4be9-b4b5-00bc8fed76ed.json
- packages/itwin/property-grid/src/e2e-tests/PropertyGrid.test.ts
- packages/itwin/tree-widget/src/e2e-tests/TreeWidget.test.ts
Make sure no class selectors are used for playwright tests (where possible) as it is recommended [here](https://playwright.dev/docs/best-practices)
> Clean up E2E tests

- change/@itwin-property-grid-react-9b3e6af5-41dc-4097-a11f-c24fcc1199ba.json
- change/@itwin-property-grid-react-f52f886f-335c-4f60-bb37-c4944a536082.json
- packages/itwin/property-grid/package.json
- packages/itwin/property-grid/pnpm-lock.yaml
Bumped `@itwin/itwinui-react` dependency version to `^3.5.0`.
Added support for `@itwin/presentation-components` version `^5.0.0`.
> [Property Grid]: Bump dependencies

- .pipelines/templates/build-steps.yaml
- change/@itwin-property-grid-react-6141cefa-e559-437e-85ff-3904f0fd207e.json
- change/@itwin-tree-widget-react-1de32109-0cd0-442d-8e17-ccf77b483c50.json
- lage.config.js
- packages/itwin/property-grid/api/property-grid-react.api.md
- packages/itwin/property-grid/api/property-grid-react.exports.csv
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/api/tree-widget-react.exports.csv
- packages/itwin/tree-widget/src/TreeWidget.ts
Currently, some packages uses api-extractor tool, which helps to check for breaking API changes.
Added a build step that will fail if `pnpm extract-api` produces a result that differs from the one that is committed.
> Add extract-api step for the PR CI build

- change/@itwin-tree-widget-react-a643610a-60a7-4820-bcdf-c67d0579ca14.json
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsVisibilityHandler.ts
- packages/itwin/tree-widget/src/components/trees/models-tree/Utils.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/Utils.test.snap
`@itwin/presentation-components` do not register ruleset anymore. Need to pass whole ruleset instead of id when loading instance keys for assembly elements.
> Tree Widget: Fix `ModelsTree` not changing visibility of child elements

- change/@itwin-tree-widget-react-e7365ba7-b435-4360-9a77-85ab88ae7fa8.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsVisibilityHandler.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsVisibilityHandler.test.ts
Newly inserted subject visibility is not changing after clicking checkbox. Need to clear subject models cache after iModel is updated.
> Tree Widget: Cannot change visibility of newly inserted subject

- change/@itwin-tree-widget-react-19b98ff9-0300-4234-b159-33ec66a1a5c5.json
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/ModelsTreeDefinition.ts
Add missing `isSubject` and `isModel` entries to nodes' extended data. Broken with https://github.com/iTwin/viewer-components-react/pull/849
> Tree widget: Fix Models tree hierarchy definition

- change/@itwin-reports-config-widget-react-24fa861a-d5b9-475e-b9f8-143e67464a4c.json
- packages/itwin/reports-config-widget/src/widget/components/ReportMappingHorizontalTile.tsx
The iModel extraction states for the mappings after it finished kept appearing after each rerender. React Strict mode made this bug more obvious.
- Simplified the logic by removing the `initialLoad` and the `jobStarted` state which was no longer necessary.
- The disabled prop that took advantage of jobStarted was also unnecessary. The whole action group gets replaced by a loading spinner anyways. This might change when eventually the component will allow for single mapping runs instead of entire iModel scoped runs, due to how the bulk extractor only keeps states on the iModel level.
> [ReportsConfig] Report mapping extractions state fix

- change/@itwin-tree-widget-react-e246135d-f170-4a16-a5ad-9f21840c31d8.json
- packages/itwin/tree-widget/src/components/trees/common/Rxjs.ts
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/internal/ModelsTreeIdsCache.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/stateless/ModelsTreeFiltering.test.ts
- Fix https://github.com/iTwin/viewer-components-react/issues/854. Refactored the query to start recursion with target instance keys instead of using recursion to create a virtual elements table and scan through it looking for targets.
- Fix https://github.com/iTwin/viewer-components-react/issues/853. We can now rebuild Subjects, Models and Categories hierarchy from our `ModelsTreeIdsCache` - no need to run additional queries.
- Since the key paths lookup performance improved drastically, put back filtering by label for categories & elements. Tried this on a few larger iModels - on L size getting the paths takes ~1 second and on XL - ~5 seconds. Seems reasonable.
- Fixed characters `%` and `_` being treated as SQLite's special characters, thus making it impossible to filter using them. …
> Tree widget: Models tree instance keys lookup optimizations

- change/@itwin-tree-widget-react-8fa3a110-48a3-4980-87c1-53690c8cd4b9.json
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/stateless/ModelsTreeFiltering.test.ts
Fixes https://github.com/iTwin/viewer-components-react/issues/880
> Tree widget: Fix Subject nodes that are leaf filter targets being auto-expanded in some cases

- change/@itwin-measure-tools-react-ee48a9ad-bfde-45a0-97db-75a631feda58.json
- packages/itwin/measure-tools/src/measure-tools-react.ts
Exporting the sheet measurement helper file in order to use it in consuming apps.
> measure-tools-react: Export SheetMeasurementHelper in measure-tools-react package

- change/@itwin-measure-tools-react-2f1c01b1-1b05-4a20-bd7d-89429de46144.json
- packages/itwin/measure-tools/src/measurements/DistanceMeasurement.ts
There was an operation priority error in the measureToolsWidget when calculating the value for sheet measurements.
> measure-tools-react: Fixes measureToolsWidget rise value for sheet measurements

- change/@itwin-tree-widget-react-b54f61d9-9108-4b0a-8fd6-c5daf692422c.json
- packages/itwin/tree-widget/public/locales/en/TreeWidget.json
- packages/itwin/tree-widget/src/components/trees/stateless/common/UseHierarchyFiltering.tsx
Closes #910 
`count` was renamed to `instanceCount` because it serves a special purpose in the translation library options type.
```ts
export interface TranslationOptions {
/** for interpolation values */
[key: string]: any;
/**
* count value used for plurals
*/
count?: number;
}
```
> Stateless tree widget: Add thousands separator to the filter dialog result count

- change/@itwin-tree-widget-react-c4738993-b001-49c1-886e-4e8021e7da18.json
- packages/itwin/tree-widget/src/components/trees/stateless/common/UseHierarchyFiltering.tsx
Closes #914 
Micro-optimization of calling `KeySet.fromJson` helps us to improve performance of key collection process by around 50% because it avoids calling inefficient `KeySet.add` method.
Even without these changes actual performance is much better that it seems. See [issue comment](https://github.com/iTwin/viewer-components-react/issues/914#issuecomment-2178732174) for more details.
> Stateless Models Tree: Improve performance of Filter Dialog initial loading.

- .pipelines/pr.yaml
- change/@itwin-tree-widget-react-e0796f73-eaee-4561-bade-fef10cb46d44.json
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsVisibilityHandler.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeComponent.test.tsx
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsVisibilityHandler.test.ts
Fixes for https://github.com/iTwin/itwinjs-core/issues/6955.
> Tree Widget 2.x: Clear models tree cache when briefcase changes

- change/@itwin-measure-tools-react-2ed96585-e212-4e2a-9671-e9802caa99e9.json
- packages/itwin/measure-tools/src/ui-2.0/MeasureToolsUiProvider.tsx
- packages/itwin/measure-tools/src/utils/types.ts
Closes #1019
[MeasureToolsUiItemsProvider ](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/measure-tools/src/ui-2.0/MeasureToolsUiProvider.tsx) can optionally have an array of StageUsages passed to its constructor. It defaults to the original value of StageUsage.General.
I also refactored the code so that all the default values are inserted within the constructor, because stageUsageList is used more than once.
> Make stage usage configurable for measure tools

- change/@itwin-tree-widget-react-4216334d-fac2-4f16-b7c0-1d6a55313d8b.json
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/components/trees/models-tree/UseModelsTree.tsx
Removed instance keys limit when custom `getFilteredPaths` function is used to show sub tree of ModelsTree. Any limit can be applied in `getFilteredPaths` implementation if necessary by throwing `FilterLimitExceededError`.
> Tree widget: Support more than 100 instances when showing subtree of ModelsTree

- change/@itwin-map-layers-2a682bd6-44ff-4576-8ec6-55bfb0a983f2.json
- packages/itwin/map-layers/src/ui/FeatureInfoUiItemsProvider.tsx
- packages/itwin/map-layers/src/ui/widget/SelectMapFormat.tsx
This feature is now ready for GA so am removing all tech preview badges.
> Remove map layers feature info tech preview badges

- change/@itwin-grouping-mapping-widget-734bd596-14af-4ef6-a408-22c1ae5a8813.json
- packages/itwin/grouping-mapping-widget/src/components/Properties/GroupProperties/GroupPropertyAction.tsx
Mainly the formula field was annoying - clearing it would cause the whole "Custom Calculation" block to collapse. This change prevents the automatic collapsing of these blocks.
> Fixed collapsing blocks when clearing input fields

- .pipelines/pr.yaml
https://github.com/iTwin/viewer-components-react/issues/1048
Looks like we've recently been on the limit and started to sometimes exceed it. For the time being I'm increasing the timeout, but will need to look into speeding up the job.
> Bump e2e tests' timeout to 2 hours

- change/@itwin-tree-widget-react-9e938ba5-ad82-41ac-8ba6-820647628d17.json
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/test/trees/common/FocusedInstancesContext.test.tsx
Consume changes from this release: https://github.com/iTwin/presentation/pull/731#issue-2570267603
> Tree widget: Bump `presentation` package dependencies

- change/@itwin-map-layers-5193bd40-6caf-439c-877f-9f57b5632bdc.json
- packages/itwin/map-layers/src/ui/widget/MapLayerManager.tsx
Map layer info tool doesn't appear on first try and only shows up when a second map layer is added or if the same on is re-added.
Solution:  put dispatchUiSyncEvent(MapLayersSyncUiEventId.MapImageryChanged) into a separate useEffect from where the set state calls are made since they need to happen synchronously
> Fix map layers feature info tool timing bug

- change/@itwin-measure-tools-react-2182f580-8b58-434f-91cb-acb164ac21e8.json
- packages/itwin/measure-tools/src/api/SheetMeasurementHelper.ts
Previously, we'd check if we were in the area of any invalid drawing for the used tool and prevent the input if there were any drawing region overlapping with the click.
Now, we check if there's any valid drawing instead which stops the bug
related to https://bentleycs.visualstudio.com/Civil-iTwin/_workitems/edit/1547446
> [measure-tools] Drawing overlap could stop you from creating measurements

- change/@itwin-measure-tools-react-5c21c471-24f9-460e-b7a0-e068a1d59aff.json
- packages/itwin/measure-tools/public/locales/en/MeasureTools.json
- packages/itwin/measure-tools/src/api/MeasurementTool.ts
- packages/itwin/measure-tools/src/api/SheetMeasurementHelper.ts
- packages/itwin/measure-tools/src/tools/MeasureAreaTool.ts
- packages/itwin/measure-tools/src/tools/MeasureDistanceTool.ts
- packages/itwin/measure-tools/src/tools/MeasureLocationTool.ts
Added tooltip to convey to user which drawings can take the measurement he's trying to use when using sheet measurements.
> [measure-tools] Show tooltip when using sheet measurement on wrong drawing type

- change/@itwin-measure-tools-react-4b81abd1-bc83-46e0-9496-7d4ab99332f6.json
- packages/itwin/measure-tools/src/ui-2.0/MeasureToolsUiProvider.tsx
Added addAdditionalToolbarItems to MeasureToolsUiItemsProvider so that applications can pass in additional measure tools to be displayed at the end of the measure tools list.
> Add support for additional Toolbar items to MeasureToolsUiItemsProvider

- change/@itwin-tree-widget-react-31b6ae5a-14a7-4851-9df2-2075087576e4.json
- packages/itwin/tree-widget/README.md
Not everyone knows that `ECSchemaRpcLocater` requires `ECSchemaRpcInterface`...
> Tree widget: Add a mention that `ECSchemaRpcLocater` requires `ECSchemaRpcInterface`

- apps/learning-snippets/package.json
- change/@itwin-tree-widget-react-5890c301-d1a0-44fa-a060-2aa5355b91f2.json
- packages/itwin/tree-widget/src/components/trees/imodel-content-tree/IModelContentTreeDefinition.ts
- packages/itwin/tree-widget/src/components/trees/imodel-content-tree/internal/IModelContentTreeIdsCache.ts
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
Apply query modifications based on this: https://github.com/iTwin/imodel-native/issues/912.
> Tree widget: Use `.Id` for navigation properties in ECSQL queries

- change/@itwin-tree-widget-react-24cc0a5c-1b2f-4569-af89-1440642ca614.json
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/models-tree/UseModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeDefinition.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeFiltering.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeHierarchyLevelFiltering.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/Utils.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeIdsCache.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
Fixes https://github.com/iTwin/viewer-components-react/issues/1101.
| | Before the change | After the change |
| --- | --- | --- |
| Number of `queryRows` requests | 385 | 1 |
| Total time to update visibility status for all nodes | ~7 s. | ~250 ms. |
> Tree widget: Reduce the number of queries being executed when always/never drawn sets change

- .github/workflows/e2e.yml
Tests failing is actually when the artifacts are most important to us...
> Publish e2e test artifacts even if tests fail

- apps/test-viewer/src/UiProvidersConfig.tsx
- apps/test-viewer/src/components/ViewerOptions.tsx
- change/@itwin-tree-widget-react-8d0932d5-74e8-4425-8fc3-727561809066.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/components/trees/common/components/Tree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/UseModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/internal/ModelsTreeNode.ts
- packages/itwin/tree-widget/src/e2e-tests/ModelsTree.test.ts
- packages/itwin/tree-widget/src/test/trees/Common.ts
Closes https://github.com/iTwin/viewer-components-react/issues/1099.
The predicate receives a node and its type to help consumers decide whether selection should be allowed or not. Example:
```tsx
function MyModelsTree(props) {
return (
<ModelsTreeComponent
{...props}
selectionPredicate={myNodesSelectionPredicate}
/>
)
}
const myNodesSelectionPredicate: ComponentProps<typeof ModelsTreeComponent>["selectionPredicate"] = ({ node, type }) => {
if (type === "element") {
return true;
}
return node.label.includes("whatever");
};
```
> Tree widget: Add `selectionPredicate` to models tree building blocks

- change/@itwin-property-grid-react-8a45f28f-060b-43dd-bc0c-9dc53f269e61.json
- packages/itwin/property-grid/src/components/FilteringPropertyGrid.tsx
- packages/itwin/property-grid/src/test/components/FilteringPropertyGrid.test.tsx
Fixes https://github.com/iTwin/viewer-components-react/issues/1131.
The decision to render the "no properties" message vs the actual properties was made based on filter matches count. However, the count was only updated on data provider change, which doesn't happen on selection change - in that case only the `onDataChanged` event is raised. Initially we have an empty source provider, so the count is resolved to `0` and afterwards, on selection changes, it was never updated.
> Fix property grid always showing "There are no properties containing non-empty values" message, when initial render is made with hidden empty values

- change/@itwin-tree-widget-react-c5e52e86-ebe6-439d-a0c6-1a895dd61a3a.json
- packages/itwin/tree-widget/src/components/trees/common/components/TreeNodeCheckbox.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1116
Visibility icon tooltip will no longer render when tooltip content is undefined.
https://github.com/user-attachments/assets/3c4383d2-ee89-4c29-877a-f7958f2217ec
The black background on icons is caused by them being disabled, removing it might cause confusion as then it will look very similar to when visibility is turned off.
> [Tree-widget]: visibility icon tooltip empty content fix

- change/@itwin-measure-tools-react-91002d1a-dbe4-4cf7-afe1-74db1b4035a2.json
- packages/itwin/measure-tools/src/api/SheetMeasurementHelper.ts
There is a bug causing a crash whenever a non-civil sheet is open.
JSON.parse is throwing an error when the jsonProperties on a sheet model are undefined.  This matches the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#exceptions) since `undefined` is not a valid string.
The tests are not passing for me on master.  I am unfamiliar with this repository, and not sure how to test my change locally.  I could provide an iModel with data to test.
> Sheets are not required to have jsonProperties

- .pipelines/pr.yaml
- .pipelines/publish.yaml
- .pipelines/templates/build-steps.yaml
- .pipelines/templates/change-files-steps.yaml
- .pipelines/templates/validate-docs-steps.yaml
Bumped node version to 22.
Additionally added work around for corepack issue https://github.com/nodejs/corepack/issues/612 that result in failure to install package manager.
> Update node version in CI pipelines

- change/@itwin-tree-widget-react-a6d91926-a46f-4d4e-a79a-d8249b2c20e4.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/Tree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/TreeRenderer.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1174.
Based on https://github.com/iTwin/presentation/pull/840.
> Tree widget: Add `filterButtonsVisibility` to `TreeRenderer`

- apps/learning-snippets/src/test/property-grid/Usage.test.tsx
- apps/test-viewer/src/UiProvidersConfig.tsx
- change/@itwin-property-grid-react-6b27dcfe-db3d-4eed-8287-9f057945cbf1.json
- packages/itwin/property-grid/README.md
- packages/itwin/property-grid/api/property-grid-react.api.md
- packages/itwin/property-grid/api/property-grid-react.exports.csv
- packages/itwin/property-grid/package.json
- packages/itwin/property-grid/pnpm-lock.yaml
- packages/itwin/property-grid/src/property-grid-react/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/property-grid-react/components/ElementList.tsx
- packages/itwin/property-grid/src/property-grid-react/components/MultiElementPropertyGrid.tsx
- packages/itwin/property-grid/src/property-grid-react/hooks/UseInstanceSelection.ts
- packages/itwin/property-grid/src/property-grid-react/hooks/UseUnifiedSelectionHandler.ts
- packages/itwin/property-grid/src/test/PropertyGridUiItemsProvider.test.tsx
- packages/itwin/property-grid/src/test/TestUtils.tsx
- packages/itwin/property-grid/src/test/components/MultiElementPropertyGrid.test.tsx
- packages/itwin/property-grid/src/test/hooks/UseInstanceSelection.test.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1168
> Property widget: Selection storage support

- change/@itwin-property-grid-react-59000ff0-e219-4344-890d-b9d908e168d4.json
- packages/itwin/property-grid/api/property-grid-react.api.md
- packages/itwin/property-grid/package.json
- packages/itwin/property-grid/src/property-grid-react/PropertyGridComponent.tsx
- packages/itwin/property-grid/src/property-grid-react/hooks/UseActionButtons.ts
- packages/itwin/property-grid/src/property-grid-react/hooks/UseTelemetryContext.tsx
We weren't tracking full public API...
> Property widget: Include unexported APIs in API report

- change/@itwin-measure-tools-react-1ead3fbf-2d2a-41c0-a721-8e0726155d9e.json
- packages/itwin/measure-tools/package.json
Add 'types' field in package.json. This fixes some issues for consumers when importing the esm package with moduleResolution: node. (export map support seems flaky in those cases.)
> [measure-tools] Add 'types' field in package.json.

- change/@itwin-measure-tools-react-6d3db761-bca1-4eaa-92ad-628ceaf37393.json
- packages/itwin/measure-tools/src/widgets/PopupToolbar.tsx
Measurement tools context popup toolbar is no longer receiving mouse down event to execute tool callback functions.
Solution:
Change event listener that closes popup toolbar to listen for click event instead of mouse down.  This allows the toolbar button to receive the mouse down event.
> Fix context popup measurement toolbar

- change/@itwin-tree-widget-react-ca9e5304-5fdd-4a5c-a69d-e928f0f97cbd.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/UseCategoriesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/EmptyTreeContent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/NoDataRenderer.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/Tree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/external-sources-tree/ExternalSourcesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/external-sources-tree/ExternalSourcesTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/UseModelsTree.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1195
Added ability to supply custom no data renderer. Also updated default no data renderer to renderer icon and added some padding.
> Tree widget: Allow custom no data message renderer

- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/TreeNodeVisibilityButton.tsx
https://github.com/iTwin/viewer-components-react/issues/1201 states the button should be displayed in partial state too
> Tree widget: Show visibility action button in partial state

- apps/test-viewer/src/components/ViewerOptions.tsx
- change/@itwin-property-grid-react-134b7ed8-408b-435b-8c98-3087d14a2167.json
- packages/itwin/property-grid/api/property-grid-react.api.md
- packages/itwin/property-grid/src/property-grid-react/PropertyGridUiItemsProvider.tsx
Consumer was trying to have two property grid widgets and only one of them worked due to widget id conflicts in AppUI system.
> Property grid: Allow creating multiple property widgets by supplying different widget ids

- apps/test-viewer/src/UiProvidersConfig.tsx
- change/@itwin-tree-widget-react-9d2dccff-032c-47bb-bcc0-9bb27169f7e4.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/tree-widget-react/components/TreeWidgetUiItemsProvider.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/tree-header/ErrorState.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/tree-header/SearchBox.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTreeButtons.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/UseCategoriesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/TreeNodeVisibilityButton.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/external-sources-tree/ExternalSourcesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeButtons.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/UseModelsTree.tsx
- packages/itwin/tree-widget/tsconfig.json
- packages/itwin/tree-widget/types.d.ts
Use default imports for importing svg until consumers supports importing svg using [import.meta.url](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta)
> Tree widget: Use default imports for svg

- packages/itwin/tree-widget/src/test/trees/categories-tree/internal/CategoriesTreeVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/categories-tree/internal/VisibilityValidation.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/VisibilityValidation.ts
closes #1230 
Following https://github.com/iTwin/viewer-components-react/pull/1265#issuecomment-2768171226
Tried a few things to reproduce the issue:
1. Tried running only those two specific tests 400 times, all of them passed.
2. Tried running all the tests in that specific file (5 times in the pipeline) that those two tests are in, all of them passed.
3. Tried running all the tree-widget tests (20 times) in the pipeline. It seems that only on Windows it started to fail (once after 4 tries, other time after 5 times). On Mac and Linux it passed every time.
4. Tried to reproduce this locally, but couldn't.
Currently, `waitFor` is used after node's visibility is changed and is used to wrap a function (`validateHierarchyVisibility`) that validates visibility of all nodes in the hierarchy. …
> Fix flaky tests

- change/@itwin-tree-widget-react-7e464ea2-07d4-4e70-9299-c05964263b49.json
- change/@itwin-tree-widget-react-f89c1633-df8e-4e89-8846-18bc29404924.json
- packages/itwin/tree-widget/src/test/trees/categories-tree/internal/CategoriesVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/categories-tree/internal/Utils.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/internal/CategoriesTreeIdsCache.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/internal/CategoriesVisibilityHandler.ts
closes #912
- Fixed Categories tree not reacting to visibility changes from Models tree. This was happening due to `onViewedCategoriesPerModelChanged` not having a listener registered in Categories tree.
- Fixed how Visibilities are determined in Categories tree. Previously if Category was under two different Models in Models tree, and Category had `PerModelCategoryVisibility.Override` set to "Hide", we would show it as "hidden" in Categories tree (while it is still visible for other model). Also, Category was not taking into a count GeometricElement's models: if "hide all" button was pressed when Models tree was opened, then viewport would not display anything, but we would show all categories as "visible" (in Categories tree).
- Added tests for those two fixes.
> Categories tree reacting to Category visibility changes from Models tree

- apps/learning-snippets/pnpm-lock.yaml
- apps/test-viewer/package.json
- apps/test-viewer/pnpm-lock.yaml
- change/@itwin-tree-widget-react-3c0d5f0d-6322-4687-b98c-a090d4527382.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/e2e-tests/CategoriesTree.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/UseIModelAccess.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/Utils.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/Tree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/VisibilityTree.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1239
Closes https://github.com/iTwin/viewer-components-react/issues/1237
Bumped `@itwin/presentation-hierachies-react` to the latest version that does correctly handles hierarchy level size limit in levels that do not support filtering.
Updated visibility tree delivered by `@itwin/tree-widget-react` package to correctly apply custom hierarchy level size limit.
> Tree widget level size config

- change/@itwin-property-grid-react-66bf838d-c359-4521-ac6f-5d56ce5e7baf.json
- packages/itwin/property-grid/src/property-grid-react/components/PropertyGridContent.tsx
Updated `filter-properties` feature reporting to reduce duplication when typing slowly. Previous implementation had 1s delay between reporting which meant that if typing filter text takes longer than 1s it will be reported again. This should fix https://github.com/iTwin/viewer-components-react/issues/1287
> [property-grid]: Improve properties filtering reporting

- change/@itwin-tree-widget-react-17f9436f-e92e-4045-bf75-b29b44ec6cc4.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeDefinition.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeDefinition.ts
Closes https://github.com/iTwin/viewer-components-react/issues/1293
Added ability to control hierarchy level filtering in `ModelsTree`. Current implementation only allows to turn on/off filtering for all hierarchy levels.
> [tree-widget]: Models tree filtering control

- packages/itwin/tree-widget/src/tree-widget-react/components/TreeWidgetUiItemsProvider.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/tree-header/ErrorState.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/tree-header/SearchBox.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTreeButtons.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/UseCategoriesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/TreeNodeVisibilityButton.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/external-sources-tree/ExternalSourcesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeButtons.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/UseModelsTree.tsx
Switching back to default import instead of `new URL` for loading svg.
> [tree-widget]: Use default imports for svg icons

- apps/test-viewer/pnpm-lock.yaml
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
Bumped hierarchies-react version to `alpha.17` with a change to use default imports for svgs instead of `URL` constructor.
> [tree-widget]: Bump hierarchies-react to `alpha.17`

- change/@itwin-measure-tools-react-df6218c8-a91a-46a6-bf67-f0c6d9b2037e.json
- packages/itwin/measure-tools/src/api/MeasurementViewTarget.ts
- packages/itwin/measure-tools/src/test/measure-tools/MeasurementViewTarget.test.ts
This PR fixes a problem with the MeasurementViewTypeClassifier where the more generic fallback types (ie. "spatial", "drawing", "sheet") are being checked before registered classifiers.
-Add some logic to ensure the registered classifiers have a higher priority than the fallback ones.
- Change the logic to allow more than 1 classifier for a given view type. While this case is a bit of a stretch, it makes it easier to gracefully handle cases where we would have multiple instances of the same viewport type (eg. multiple civil sections) and each section managing its own view type classifier.
> [measure-tools-react] Bugfix. ViewTypeClassifier not using registered classifiers

- apps/learning-snippets/src/test/tree-widget/FilteredPaths.test.tsx
- change/@itwin-tree-widget-react-4979d818-712d-4f2a-b27e-ac9adef6517b.json
- packages/itwin/tree-widget/README.md
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/UseModelsTree.tsx
closes #[1319](https://github.com/iTwin/viewer-components-react/issues/1319).
Added documentation explaining `getFilteredPaths` and its usage
> Update `getFilteredPaths` documentation

- change/@itwin-tree-widget-react-e0e85de3-ea1f-48ff-b8da-1cb2f72be783.json
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeIdsCache.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/VisibilityValidation.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
> Category count query fix

- apps/performance-tests/src/tree-widget/ModelsTree.test.ts
- apps/performance-tests/src/tree-widget/VisibilityUtilities.ts
- apps/performance-tests/src/util/TestReporter.cts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
In https://github.com/iTwin/viewer-components-react/pull/1364 integration test was added which was failing on release pipeline. Created a similar test under performance tests and removed the old one.
> Move integration test to performance tests

- change/@itwin-tree-widget-react-28af0add-8cae-4243-83fc-abd20b9a8cd5.json
- packages/itwin/tree-widget/package.json
Added missing peer dependecies:
- `@itwin/core-bentley` https://github.com/iTwin/viewer-components-react/blob/532f6f6a5d896c981d04a851f72b5960b3eb08f3/packages/itwin/tree-widget/src/tree-widget-react/TreeWidget.ts#L6
- `@itwin/core-common` https://github.com/iTwin/viewer-components-react/blob/532f6f6a5d896c981d04a851f72b5960b3eb08f3/packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTreeDefinition.ts#L6
- `@itwin/presentation-common` https://github.com/iTwin/viewer-components-react/blob/532f6f6a5d896c981d04a851f72b5960b3eb08f3/packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/UseHierarchyFiltering.tsx#L10
- `@itwin/presentation-frontend` https://github.com/iTwin/viewer-components-react/blob/532f6f6a5d896c981d04a851f72b5 …
> [Tree widget]: Add missing peers

- apps/learning-snippets/src/test/tree-widget/SubTreePaths.test.tsx
- change/@itwin-tree-widget-react-0be4b147-32c7-4f57-be65-cc3ee8db2099.json
- packages/itwin/tree-widget/README.md
Added learning snippet for `getSubTreePaths` usage.
> [Tree-widget]: Add learning snippet for `getSubTreePaths`

- change/@itwin-tree-widget-react-b7a83ae4-1cc2-4eb5-b8ce-73f7243e26e3.json
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
For the test case at hand, there were ~1900 where clauses, so they were all placed into a single huge query. On a local briefcase the query took ~3 minutes to run, on GPB - more than 5 minutes.
Splitting it into chunks of 100 where clauses allows us to execute them in parallel and in GPB case they take ~11 seconds.
> Tree widget: Make model category elements query chunks smaller

- apps/learning-snippets/src/test/tree-widget/FilteredPaths.test.tsx
- change/@itwin-tree-widget-react-d96e3dbf-a31f-4135-b74a-305c4c38ac62.json
- packages/itwin/tree-widget/README.md
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/test/trees/common/UseNodeHighlighting.test.tsx
- packages/itwin/tree-widget/src/test/trees/common/Utils.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTreeFiltering.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/UseNodeHighlighting.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/Utils.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/UseModelsTree.tsx
Made it possible in Models tree to apply given filter string only to a subset of the hierarchy (e.g. up to Model nodes, as shown in the updated README example).
Changes made:
1. Ability to use active filter string in the `getFilteredPaths` prop function was non-functional, because we couldn't return `undefined` when the `filter = undefined`. Now we can, and that means that filtering should not be applied.
2. Don't disable the filtering entry point when `getFilteredPaths` prop is provided.
3. Only highlight filter matches on nodes that are filter targets, only recurse into node's children if we know there are filter targets in there. This makes sure we don't highlight substring on nodes that are not filter targets, even if they have a matching substring (e.g. if we only search for Models, …
> Tree widget: Allow returning `undefined` paths from `getFilteredPaths` prop function

- change/@itwin-measure-tools-react-1a5a6a2c-f7a8-4ec8-88ef-19284186d546.json
- package.json
- packages/itwin/measure-tools/src/api/FormatterUtils.ts
- packages/itwin/measure-tools/src/measurements/AngleMeasurement.ts
- packages/itwin/measure-tools/src/measurements/AreaMeasurement.ts
- packages/itwin/measure-tools/src/measurements/DistanceMeasurement.ts
- packages/itwin/measure-tools/src/measurements/LocationMeasurement.ts
- packages/itwin/measure-tools/src/measurements/RadiusMeasurement.ts
- packages/itwin/measure-tools/src/test/measure-tools/AngleMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/DistanceMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/RadiusMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/_Setup.test.ts
Closes https://github.com/iTwin/viewer-components-react/issues/1415.
Falling back to QuantityType was working for iModels that don't have the specified KoQ, however aggregatableValue fields did not include that fallback because it was still trying to use an undefined formatSpec associated with the missing KoQ, when other fields are using the fallbacks. Fixed it so now aggregatableValue fields will use fallback formatter specs as well.
Also, bumped pnpm package manager version in the root of repo, to address [bug](https://github.com/pnpm/pnpm/issues/9792) with pnpm
> Fix aggregatableValues missing formatting in Measurement widgets

- change/@itwin-measure-tools-react-95ece8b6-df5c-41c3-b011-4963415a12c2.json
- packages/itwin/measure-tools/src/api/FormatterUtils.ts
- packages/itwin/measure-tools/src/api/MeasurementManager.ts
- packages/itwin/measure-tools/src/measurements/DistanceMeasurement.ts
As stated in PR title, have the widget update to format changes without selecting/unselecting (matching property-grid behavior)
- Also, updating bearing property in distance measurement widget, previously it had used hard coded bearing formatProps, now it'll use bearing format coming from FormatsProvider, falling back to hard coded props if formatsProvider can't find any.
> Update MeasurementWidget to react to format change events

- change/@itwin-property-grid-react-bb732407-464d-4b9a-81cd-72a0f9356e81.json
- packages/itwin/property-grid/src/property-grid-react/PropertyGridUiItemsProvider.tsx
- packages/itwin/property-grid/src/test/PropertyGridUiItemsProvider.test.tsx
Fixes https://github.com/iTwin/viewer-components-react/issues/1425
> [property-grid]: Open property grid when selection already contains something

- change/@itwin-map-layers-ac4194f0-f2e3-4bdd-86a8-dd75972e07e6.json
- packages/itwin/map-layers/src/public/locales/en/mapLayers.json
- packages/itwin/map-layers/src/ui/Interfaces.ts
- packages/itwin/map-layers/src/ui/widget/MapLayerManager.scss
- packages/itwin/map-layers/src/ui/widget/MapLayerManager.tsx
The maplayers header label was previously removed but after discussion, this is being restored but with an optional flag to hide it.
Previous PR to remove:  https://github.com/iTwin/viewer-components-react/pull/1261/files
> [map-layers] Restore header label and add optional flag to hide it

- apps/test-viewer/src/UiProvidersConfig.tsx
- change/@itwin-measure-tools-react-efa5cf9f-4e6a-4c7f-8a0f-4f2bfc3b3d03.json
- packages/itwin/measure-tools/src/measurements/DistanceMeasurement.ts
To format and display bearing in Distance measurements, we need a revolution unit to lookup - `Units.REVOLUTION` from the units schema is one example. Problem is there are iModels out there that don't have the units schema. In that case, an error would be thrown, and the widget wouldn't show up. 
Making the display of bearing calculation be opt-in again - applications will have to supply a KoQ and persistenceUnit to the measure tools ui provider for bearing, which would then allow unit lookup and formatting.
Image of the measurement widget, without 'Bearing' property shown, when I comment out passing in a koq and persistenceUnit in the test viewer (also fixed a typo in the KoQ for Units.BEARING)
> [measure-tools] Make bearing calculation opt in again for Distance measurements

- change/@itwin-measure-tools-react-f6485d69-9645-4b8b-b09e-cd1608c32857.json
- packages/itwin/measure-tools/src/api/Polygon.ts
- packages/itwin/measure-tools/src/measurements/AngleMeasurement.ts
- packages/itwin/measure-tools/src/measurements/AreaMeasurement.ts
- packages/itwin/measure-tools/src/measurements/DistanceMeasurement.ts
- packages/itwin/measure-tools/src/measurements/LocationMeasurement.ts
- packages/itwin/measure-tools/src/measurements/RadiusMeasurement.ts
- packages/itwin/measure-tools/src/test/measure-tools/AngleMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/AreaMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/DistanceMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/LocationMeasurement.test.ts
- packages/itwin/measure-tools/src/test/measure-tools/RadiusMeasurement.test.ts
Fix performance problem for measurements. Problem was onMouseMove, a new measurement object is initialized, and inside the ctor of each measurement they try to repopulate the formatterSpec cache if it couldn't retrieve a formatSpec for the KoQ the measurement uses. For iModels that never has the relevant KoQ, that happens every single time. Removed the repopulating code from the ctor.
Example of the problem in question, with an iModel that doesn't have the KoQ:
https://github.com/user-attachments/assets/a8ba5e63-3f25-4ed3-8e8d-e2921f3ff853
Example of an iModel that does have the KoQ
https://github.com/user-attachments/assets/19a6ad7b-4eb9-4928-b57f-af2baf8cf158
Also fixed area polygon's text marker when no KoQ schema found. The code to generate the polygon's inner text marker wasn't using …
> [measure-tools] Fix performance problem, missing text marker for Area polygon

- change/@itwin-tree-widget-react-c2a5489f-ac72-4be2-9bf9-ea1edb1514a1.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/test/trees/common/UseHierarchyVisibility.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/UseHierarchyVisibility.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/common/components/TreeNodeCheckbox.tsx
closes https://github.com/iTwin/viewer-components-react/issues/1411
> Tree widget: Add "loading" state to `TreeNodeCheckboxState` type
