iTwin/viewer-components-react

- README.md
Updated readme with getting started steps. Copied from imjs repo, and removed what I thought to be irrelevant like extract-api and changes to that.
> Updated readme with getting started steps

- common/changes/@bentley/tree-widget-react/cleanup-headers_2020-07-07-19-43.json
- packages/tree-widget/src/TreeWidget.ts
- packages/tree-widget/src/components/IconButton.tsx
- packages/tree-widget/src/components/TreeWidgetComponent.tsx
- packages/tree-widget/src/components/TreeWidgetControl.tsx
- packages/tree-widget/src/components/search-bar/Popup.tsx
- packages/tree-widget/src/components/search-bar/SearchBar.scss
- packages/tree-widget/src/components/search-bar/SearchBar.tsx
- packages/tree-widget/src/components/search-bar/SearchBox.scss
- packages/tree-widget/src/components/search-bar/SearchBox.tsx
- packages/tree-widget/src/components/trees/CategoriesTree.tsx
- packages/tree-widget/src/components/trees/ModelsTree.scss
- packages/tree-widget/src/components/trees/ModelsTree.tsx
- packages/tree-widget/src/tree-widget-react.ts
Update all the copyright headers to be consistent
> clean up copyright headers

- common/changes/@bentley/imodel-select-react/Use-Themed-colors_2020-07-02-20-31.json
- packages/imodel-select/src/components/BlockingPrompt.scss
- packages/imodel-select/src/components/IModelCard.scss
- packages/imodel-select/src/components/IModelCard.tsx
- packages/imodel-select/src/components/IModelList.scss
- packages/imodel-select/src/components/IModelSelector.scss
- packages/imodel-select/src/components/ProjectDialog.scss
- packages/imodel-select/src/components/ProjectDropdown.scss
- packages/imodel-select/src/components/ProjectDropdown.tsx
- packages/imodel-select/src/components/ProjectTabs.scss
Replace hard-coded color specifications with themeable color specifications.
> Update to support dark/light themes

- .github/CODEOWNERS
- common/changes/@bentley/tree-widget-react/classifications-tree_2020-07-07-12-33.json
- common/changes/@bentley/tree-widget-react/classifications-tree_2020-07-13-09-00.json
- packages/tree-widget/src/components/rulesets/ClassificationSystems.json
- packages/tree-widget/src/components/trees/ClassificationsTree.tsx
- packages/tree-widget/src/components/trees/TreeWithRuleset.tsx
- packages/tree-widget/src/components/trees/TreeWithRulesetTree.scss
Open source the implementation of classifications tree.
> Add Classifications tree.

- common/changes/@bentley/tree-widget-react/tree-fixes_2020-07-28-20-46.json
- packages/tree-widget/src/components/TreeWidgetComponent.scss
- packages/tree-widget/src/components/trees/CategoriesTree.tsx
1. Added invert functionality to categories tree to be consistent with models tree
2. Added forced 100% height on content wrapper to avoid issues when using iframes to host design review in Teams.
> Tree fixes

- README.md
- common/changes/@bentley/property-grid-react/maint-UpdatePkgJson_2020-08-20-21-28.json
- common/changes/@bentley/tree-widget-react/maint-UpdatePkgJson_2020-08-20-21-37.json
- packages/property-grid/package.json
- packages/tree-widget/README.md
Update property-grid-react pkg deps to be alphabetical
Add npm badge so i dont have to navigate to the pkg dir or npm to see the latest version
> add minor updates

- common/changes/@bentley/property-grid-react/react-spring-peer-dep_2020-08-24-19-36.json
- packages/property-grid/package.json
Needed to avoid versioning issues in IT1 which cause test failures
> React spring as peer dep

- common/changes/@bentley/property-grid-react/react-spring-cjs-fix_2020-08-25-16-22.json
- common/git-hooks/pre-commit
- packages/property-grid/src/components/MultiElementPropertyGrid.tsx
Fix jest test failures in IT1 by importing from the CommonJS react-spring/renderprops file. This was suggested as a fix in this comment:
https://github.com/react-spring/react-spring/issues/601#issuecomment-475125021
> React-Spring CommonJS import for Jest

- common/changes/@bentley/imodel-react-hooks/fix-alphabetize-imodel-react-hooks-pkgjson_2020-10-14-14-43.json
- packages/imodel-react-hooks/package.json
> alphabetized package.json in imodel-react-hooks

- common/changes/@bentley/imodel-react-hooks/fix-update-readme-on-useMarker-size-types_2020-10-28-14-53.json
- packages/imodel-react-hooks/README.md
- update useMarker README.md on useMarkerOptions.size type changes from Marker API
- also includes imageSize and imageOffset type documentation
- small wording decision changes in other parts of README
> update useMarker README.md on useMarkerOptions.size type changes from Marker API

- .github/CODEOWNERS
- .github/workflows/sanity.yml
The current codeowners file isn't working correctly due to a mis-configuration.  This workflow has been helpful in finding issues with the one in iModel.js.
> Add a codeowners file sanity check workflow

- common/changes/@bentley/tree-widget-react/models-tree-load-fix_2021-02-26-18-25.json
- packages/tree-widget/src/components/trees/ModelsTree.tsx
Fix models tree show all, invert and toggles to load models properly.
> Models Tree: Load Models Fix

- common/changes/@bentley/geo-tools-react/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/imodel-content-tree-react/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/imodel-react-hooks/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/imodel-select-react/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/markup-frontstage-react/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/measure-tools-react/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/property-grid-react/successful_warnings_2021-07-08-18-30.json
- common/changes/@bentley/tree-widget-react/successful_warnings_2021-07-08-18-30.json
- common/config/rush/command-line.json
- packages/geo-tools/package.json
- packages/imodel-content-tree/package.json
- packages/imodel-react-hooks/package.json
- packages/imodel-select/package.json
- packages/markup-frontstage/package.json
- packages/measure-tools/package.json
- packages/property-grid/package.json
- packages/tree-widget/package.json
This should fix the ci and unblock  #116
> update build command to allow warnings in a successful build to fix ci

- common/changes/@bentley/tree-widget-react/updateTreeBarrel_2021-08-09-19-48.json
- packages/tree-widget/src/tree-widget-react.ts
Updated Tree Widget barrel file to export the UiProvider
> Updated Tree Widget barrel file

- common/changes/@bentley/measure-tools-react/measurement-sync-with-internal_2021-08-18-20-00.json
- common/changes/@bentley/measure-tools-react/measurement-sync-with-internal_2_2021-08-18-20-00.json
- common/changes/@bentley/measure-tools-react/measurement-sync-with-internal_3_2021-08-18-20-00.json
- packages/measure-tools/public/locales/en/MeasureTools.json
- packages/measure-tools/src/api/FeatureTracking.ts
- packages/measure-tools/src/api/Measurement.ts
- packages/measure-tools/src/api/MeasurementManager.ts
- packages/measure-tools/src/api/MeasurementTool.ts
- packages/measure-tools/src/tools/MeasureAreaTool.ts
- packages/measure-tools/src/tools/MeasureDistanceTool.ts
- packages/measure-tools/src/widgets/MeasurementActionToolbar.tsx
Pull over the internal updates made to the tool as not everyone is using this version yet.
After this change, we can hopefully make that the case and all new updates will be made directly to this package.
> Update measurement tools with internal updates

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
- common/changes/@bentley/geo-tools-react/rm-psuedo_2021-09-16-01-14.json
- common/changes/@bentley/imodel-select-react/rm-psuedo_2021-09-16-01-14.json
- common/changes/@bentley/markup-frontstage-react/rm-psuedo_2021-09-16-01-14.json
- common/changes/@bentley/measure-tools-react/rm-psuedo_2021-09-16-01-14.json
- common/changes/@bentley/property-grid-react/rm-psuedo_2021-09-16-01-14.json
- common/changes/@bentley/tree-widget-react/rm-psuedo_2021-09-16-01-14.json
- packages/geo-tools/package.json
- packages/imodel-select/package.json
- packages/markup-frontstage/package.json
- packages/measure-tools/package.json
- packages/property-grid/package.json
- packages/tree-widget/package.json
- stop delivering psuedo localized strings
- add devcontainer to use with workspaces
> stop delivering psuedo localized strings, add devcontainer to use with workspaces

- common/changes/@bentley/property-grid-react/Styling-updates_2021-09-28-15-41.json
- packages/property-grid/public/locales/en/PropertyGrid.json
- packages/property-grid/src/components/ElementList.scss
- packages/property-grid/src/components/ElementList.tsx
- packages/property-grid/src/components/MultiElementPropertyGrid.scss
- packages/property-grid/src/components/PropertyGrid.scss
- packages/property-grid/src/components/PropertyGrid.tsx
Several styling changes:
1. Force header to be a consistent size (50px), this way transitions look better.
2. Show ellipsis for clipped text.
3. Align back button better to the left.
4. Show Element Lists in the header.
> Styling updates

- common/changes/@bentley/breakdown-trees-react/exportDataTrees_2021-11-12-13-42.json
- packages/breakdown-trees/package.json
- packages/breakdown-trees/src/breakdown-trees-react.ts
- packages/breakdown-trees/tsconfig.json
Export data trees to use from consuming applications.
> Export data trees

- common/changes/@bentley/breakdown-trees-react/testSetup_2021-11-29-12-35.json
- common/config/rush/pnpm-lock.yaml
- packages/breakdown-trees/.npmignore
- packages/breakdown-trees/mocha.opts
- packages/breakdown-trees/package.json
- packages/breakdown-trees/src/Controllers/TreeWithRulesetControllerBase.ts
- packages/breakdown-trees/src/Views/MoreOptionsButton.tsx
- packages/breakdown-trees/src/breakdown-trees-react.ts
- packages/breakdown-trees/src/test/OptionItemHandlers/ClipAtSpacesHandler.test.ts
- packages/breakdown-trees/src/test/OptionItemHandlers/GenericOptionItemHandler.test.ts
- packages/breakdown-trees/src/test/OptionItemHandlers/LabelHandler.test.ts
- packages/breakdown-trees/src/test/OptionItemHandlers/TopViewHandler.test.ts
- packages/breakdown-trees/src/test/TreeComponents.test.snap
- packages/breakdown-trees/src/test/TreeComponents.test.tsx
- packages/breakdown-trees/src/test/TreeNodeFunctionsToolbar.test.snap
- packages/breakdown-trees/src/test/TreeNodeFunctionsToolbar.test.tsx
- packages/breakdown-trees/src/test/Utils.tsx
- packages/breakdown-trees/src/test/assets/RulesList.json
- packages/breakdown-trees/src/test/assets/SpatialBreakdown.json
- packages/breakdown-trees/src/test/functionalityProviders/BuildingClipPlanesProvider.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/ClearSectionsFunctionalityProvider.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/FunctionalityProviderTestUtils.ts
- packages/breakdown-trees/src/test/functionalityProviders/SelectRelatedFunctionalityProvider.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/SpaceClipPlanesProvider.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/StoryClipPlanesProvider.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/ToggledTopFitViewFunctionalityProvider.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/TreeNodeFunctionalityMapper.test.ts
- packages/breakdown-trees/src/test/functionalityProviders/ZoomFunctionalityProvider.test.ts
- packages/breakdown-trees/src/test/scripts/copy-test-setup.js
- packages/breakdown-trees/src/test/scripts/setup-tests.js
Test Setup done.
All tests are added for the tree related components.
> Test setup

- common/changes/@bentley/breakdown-trees-react/removeTestUtilExport_2021-12-06-12-47.json
- packages/breakdown-trees/src/breakdown-trees-react.ts
Need to remove the export statement for a file that lies within test directory as that is producing a crash while running test in consuming application.
> Remove test util export

- common/changes/@itwin/property-grid-react/cjs-scss_2022-02-01-21-35.json
- common/changes/@itwin/tree-widget-react/cjs-scss_2022-02-01-21-35.json
- packages/itwin/property-grid/src/components/ElementList.scss
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.scss
- packages/itwin/property-grid/src/components/PropertyGrid.scss
- packages/itwin/tree-widget/src/components/IconButton.scss
- packages/itwin/tree-widget/src/components/TreeWidgetComponent.scss
- packages/itwin/tree-widget/src/components/header/TreeHeader.scss
- packages/itwin/tree-widget/src/components/search-bar/Popup.scss
- packages/itwin/tree-widget/src/components/search-bar/SearchBar.scss
- packages/itwin/tree-widget/src/components/search-bar/SearchBox.scss
- packages/itwin/tree-widget/src/components/trees/CategoriesTree.scss
- packages/itwin/tree-widget/src/components/trees/ModelsTree.scss
- packages/itwin/tree-widget/src/components/trees/TreeWithRulesetTree.scss
Needed for when you link this repo with the core repo
> update scss to be pulled from cjs dir

- common/changes/@itwin/breakdown-trees-react/fix-test-script_2022-02-03-17-15.json
- packages/itwin/breakdown-trees/package.json
Fix test script to support cjs
> Fix test script

- common/changes/@itwin/grouping-mapping-widget/aspect-alias-query-correction_2022-02-04-23-18.json
- packages/itwin/grouping-mapping-widget/README.md
- packages/itwin/grouping-mapping-widget/src/widget/components/QueryBuilder.ts
- packages/itwin/grouping-mapping-widget/src/widget/components/utils.tsx
- Added an ECInstanceId alias for aspect element ids in group query selection.
- Fixed some readme mistakes
> README updated and query fix

- common/changes/@itwin/grouping-mapping-widget/struct-fix_2022-02-12-01-09.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupPropertyAction.tsx
Fixed the missing struct properties within group property selection.
> [Grouping&Mapping] Fixed missing struct properties

- common/changes/@itwin/grouping-mapping-widget/navigation-elements-properties_2022-03-09-02-54.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupAction.scss
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupPropertyAction.tsx
Initial support, hardcoded values due to impending UI refresh and UI not supporting multiple selections from the same class.
> [Grouping&Mapping] Model and Category Support in group properties

- common/changes/@itwin/tree-widget-react/bills-addAbilityToSpecifyDefaultWidgetLocation_2022-03-25-15-52.json
- packages/itwin/tree-widget/src/components/TreeWidgetUiItemsProvider.tsx
- packages/itwin/tree-widget/src/types.ts
Design Review would like the ability to set the default location to the left panel.
> Add ability for user to supply default location for Tree Widget

- common/changes/@itwin/one-click-lca-react/readme-typo_2022-04-07-15-54.json
- packages/itwin/one-click-lca-widget/README.md
Fix instruction typo in readme to match package name
> readme typo fix

- common/changes/@itwin/grouping-mapping-widget/query-keywords-rework_2022-04-12-21-50.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupAction.tsx
Scrapped the old query generation that involved unions and replaced it with FK logic. Also now searches through types.
> [Grouping&Mapping] Query keywords query refactor

- common/changes/@itwin/property-grid-react/property-grid-react-0.4.2_2022-05-10-12-24.json
- packages/itwin/property-grid/package.json
manually bump to 0.4.2 to allow previous commits to be published
> [property-grid-react] manually bump to 0.4.2

- common/changes/@itwin/grouping-mapping-widget/description-not-required_2022-05-12-21-38.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupAction.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/MappingAction.tsx
Widget was requiring descriptions for mappings and groups. Removed it as platform does not require it.
> [Grouping&Mapping] Description no longer required

- common/changes/@itwin/grouping-mapping-widget/gm-multi-selection_2022-06-14-22-33.json
- packages/itwin/grouping-mapping-widget/src/widget/components/QueryBuilder.ts
> [Grouping&Mapping] Union multiple selected classes

- common/changes/@itwin/grouping-mapping-widget/gm-category_2022-06-16-15-02.json
- common/changes/@itwin/reports-config-widget-react/gm-category_2022-06-16-22-37.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupQueryBuilderContainer.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/Grouping.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/QueryBuilder.ts
- packages/itwin/reports-config-widget/src/test/ReportMappings.test.tsx
Bug fix:
- category query cannot be resolved
- visibility on overlapped groups
- reset view responsiveness
> [Grouping&Mapping] fix category query and visibility

- common/changes/@itwin/grouping-mapping-widget/HZ-visibilty_2022-07-08-20-07.json
- packages/itwin/grouping-mapping-widget/src/widget/components/Grouping.tsx
> [Grouping & Mapping] Add color legends for groups

- common/changes/@itwin/reports-config-widget-react/missing-dep_2022-08-03-06-22.json
- common/config/rush/pnpm-lock.yaml
- packages/itwin/reports-config-widget/package.json
> [ReportsConfig] Missing dep

- common/changes/@itwin/tree-widget-react/jaykumarpatel-defaultTree-view_2022-09-12-18-17.json
- packages/itwin/tree-widget/public/locales/en/TreeWidget.json
- packages/itwin/tree-widget/src/components/TreeWidgetUiItemsProvider.tsx
- packages/itwin/tree-widget/src/types.ts
- Added the change for setting up defaultTree from the viewer component
- Updated the naming for "model" : "models"
> Add new `defaultTreeId` prop to specify default tree for TreeWidgetUiItemsProvider

- common/changes/@itwin/grouping-mapping-widget/gm-test_2022-10-02-17-37.json
- packages/itwin/grouping-mapping-widget/README.md
- packages/itwin/grouping-mapping-widget/package.json
- packages/itwin/grouping-mapping-widget/src/test/GroupingMappingCustomUI.test.tsx
- BUG FIX: pictures in README on NPM registry cannot be found
- Test grouping mapping extensibility
> [G&M] Grouping Mapping Widget UI Tests

- common/changes/@itwin/grouping-mapping-widget/key_issue_2022-10-12-22-45.json
- packages/itwin/grouping-mapping-widget/src/widget/components/GroupPropertyUtils.ts
Key was not unique enough in some instances.
> [G&M] Fixed key issue

- common/changes/@itwin/grouping-mapping-widget/test-fix-attempt_2022-12-16-07-48.json
- packages/itwin/grouping-mapping-widget/jest.config.js
- packages/itwin/grouping-mapping-widget/src/test/GroupingMappingCustomUI.test.tsx
Tests kept timing out so I increased timeout time to 20s.
> Unit test fix attempt

- common/changes/@itwin/grouping-mapping-widget/api-update_2023-03-06-20-22.json
- common/changes/@itwin/one-click-lca-react/api-update_2023-03-06-20-22.json
- common/changes/@itwin/reports-config-widget-react/api-update_2023-03-06-20-22.json
- common/config/rush/pnpm-lock.yaml
- packages/itwin/grouping-mapping-widget/package.json
- packages/itwin/one-click-lca-widget/package.json
- packages/itwin/one-click-lca-widget/src/components/ExportModal.tsx
- packages/itwin/reports-config-widget/package.json
Should hopefully fix https://github.com/iTwin/itwinjs-core/issues/5158.
> Insights Client Bump

- common/changes/@itwin/tree-widget-react/Clear_elements_with_exclusive_on_show_all_2023-03-20-05-55.json
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeComponent.tsx
> Ensure that the "Show all" button shows all models when there are models with an "exclusive" flag

- common/changes/@itwin/grouping-mapping-widget/bug_2023-04-15-04-36.json
- packages/itwin/grouping-mapping-widget/src/widget/components/Grouping.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/Mapping.tsx
These sorts were sorting in place causing very rare race condition issues (list mutating in the middle of for loops...) due to the state becoming uncontrolled. 
Found this issue in another branch in the middle of refactoring.
> [G&M] Visualization race condition fix

- common/config/azure-pipelines/templates/build-publish.yaml
> rush publish --include-all

- common/changes/@itwin/tree-widget-react/conditional_trees_2023-04-24-10-24.json
- common/changes/@itwin/tree-widget-react/rework_additional_trees_handling_2023-04-14-14-58.json
- packages/itwin/tree-widget/public/locales/en/TreeWidget.json
- packages/itwin/tree-widget/src/components/TreeWidgetComponent.scss
- packages/itwin/tree-widget/src/components/TreeWidgetComponent.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/375
> Tree Widget: Add ability to conditionally show/hide trees in widget

- common/changes/@itwin/tree-widget-react/Avoid_reseting_branch_state_when_parent_node_is_collapsed_2023-05-18-06-23.json
- packages/itwin/tree-widget/src/components/trees/category-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
> Tree Widget: Keep child nodes state the same after parent node re-expands

- common/changes/@itwin/tree-widget-react/_Disable_root_node_colapsing_in_models_tree_2023-05-18-04-57.json
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeBase.scss
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeRenderer.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTree.test.snap
- packages/itwin/tree-widget/src/test/trees/models-tree/ModelsTree.test.tsx
> Models Tree: Disable root node colapsing

- common/changes/@itwin/tree-widget-react/Avoid_reseting_branch_state_when_parent_node_is_collapsed_2023-05-18-06-23.json
- common/changes/@itwin/tree-widget-react/Fix_invert_button_2023-04-18-16-20.json
- common/changes/@itwin/tree-widget-react/Keep_eye_checkbox_position_static_on_horizontal_scroll_2023-05-26-11-12.json
- common/changes/@itwin/tree-widget-react/Use_searchBox_component_from_itwinui_react_2023-05-29-11-40.json
- common/changes/@itwin/tree-widget-react/_Disable_root_node_colapsing_in_models_tree_2023-05-18-04-57.json
- common/changes/@itwin/tree-widget-react/rework_additional_trees_handling_2023-04-14-14-58.json
- common/changes/@itwin/tree-widget-react/tree-widget-external-sources-tree_2023-04-07-13-59.json
- common/changes/@itwin/tree-widget-react/tree-widget-models-tree-hierarchy-configuration_2023-05-11-08-05.json
- common/config/rush/version-policies.json
Updated change types and version policy
> Tree widget: Update change types

- apps/test-viewer/src/UiProvidersConfig.tsx
- common/api/property-grid-react.api.md
- common/api/summary/property-grid-react.exports.csv
- common/changes/@itwin/property-grid-react/property_grid_ancestors_navigation_2023-06-13-14-41.json
- packages/itwin/property-grid/src/components/MultiElementPropertyGrid.tsx
- packages/itwin/property-grid/src/hooks/UseInstanceSelection.ts
- packages/itwin/property-grid/src/test/components/MultiElementPropertyGrid.test.tsx
- packages/itwin/property-grid/src/test/hooks/UseInstanceSelection.test.ts
Closes https://github.com/iTwin/viewer-components-react/issues/534
> Property Widget: Ancestors navigation customization

- common/changes/@itwin/property-grid-react/property_grid_npm_ignore_2023-07-18-15-00.json
- packages/itwin/property-grid/.npmignore
Add `test` folder to `.npmignore`
> PropertyGrid: Do not publish tests to npm

- common/api/property-grid-react.api.md
- common/api/summary/property-grid-react.exports.csv
- common/changes/@itwin/property-grid-react/property_grid_selected_elements_button_2023-08-02-08-34.json
- packages/itwin/property-grid/src/components/FilteringPropertyGrid.tsx
- packages/itwin/property-grid/src/components/PropertyGrid.tsx
- packages/itwin/property-grid/src/components/PropertyGridContent.tsx
- packages/itwin/property-grid/src/components/SingleElementPropertyGrid.tsx
- packages/itwin/property-grid/src/test/components/PropertyGrid.test.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/592
> Property Widget: Render header when too many element selected

- common/api/property-grid-react.api.md
- common/api/summary/property-grid-react.exports.csv
- common/changes/@itwin/property-grid-react/property_grid_override_menu_items_2023-08-03-14-05.json
- packages/itwin/property-grid/src/hooks/UseContextMenu.tsx
- packages/itwin/property-grid/src/test/hooks/UseContextMenu.test.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/595
> Property Widget: Add ability to override default context menu items

- common/changes/@itwin/property-grid-react/tree_property_widget_changelogs_2023-08-07-07-44.json
- common/changes/@itwin/tree-widget-react/tree_property_widget_changelogs_2023-08-07-07-44.json
- packages/itwin/property-grid/CHANGELOG.json
- packages/itwin/tree-widget/CHANGELOG.json
Closes https://github.com/iTwin/viewer-components-react/issues/601
> Tree Widget & Property Widget: Purge old changelogs

- common/changes/@itwin/property-grid-react/property_grid_scrollbar_fix_2023-08-07-08-50.json
- packages/itwin/property-grid/src/components/PropertyGridContent.scss
- packages/itwin/property-grid/src/components/PropertyGridContent.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/603
> Property Widget: Fix scrollbar not appearing

- common/changes/@itwin/measure-tools-react/fix-toolbar-close_2023-08-18-19-22.json
- packages/itwin/measure-tools/src/widgets/MeasurementActionToolbar.tsx
- packages/itwin/measure-tools/src/widgets/PopupToolbar.tsx
Somehow the code for this was there but not hooked up.
> [Measurement Tools] Fix toolbar close for click outside

- common/changes/@itwin/grouping-mapping-widget/arnobm-restore-import-mapping-button_2023-08-24-18-05.json
- packages/itwin/grouping-mapping-widget/src/widget/components/Mappings.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/MappingsView.tsx
- packages/itwin/grouping-mapping-widget/src/widget/components/hooks/useMappingsOperations.ts
Added missing state to restore missing import mapping button to default UI.
> [G&M] restore import mapping button

- common/changes/@itwin/property-grid-react/make_elements_list_sorted_2023-08-23-13-59.json
- packages/itwin/property-grid/src/components/ElementList.tsx
- packages/itwin/property-grid/src/test/components/ElementList.test.tsx
Sort selected items by their label in an ascending order.
> Make elements list sorted

- common/changes/@itwin/imodel-react-hooks/imodel-react-hooks-4_2023-09-29-15-10.json
- common/config/rush/pnpm-lock.yaml
- packages/itwin/imodel-react-hooks/package.json
- update @itwin/imodel-react-hooks to itwin.js 4
- had to bump update to minimum required version of itwin.js 4
> update @itwin/imodel-react-hooks to itwin.js 4

- common/changes/@itwin/grouping-mapping-widget/uyen-extraction-filter-checkboxes_2023-09-29-21-00.json
- packages/itwin/grouping-mapping-widget/src/widget/components/ExtractionLogCustomFilter.tsx
Changed extraction log custom filter radio buttons to checkboxes for multiple selections.
> [G&M] Changed extraction log filter radio buttons to checkboxes

- common/changes/@itwin/measure-tools-react/fix-measure-tools-deliver_2023-10-03-16-23.json
- packages/itwin/measure-tools/.npmignore
- packages/itwin/measure-tools/README.md
- packages/itwin/measure-tools/package.json
- update readme
- dont deliver test files
- npmignore wont work when package.json has a files property
> [measure-tools] cleanup readme and npmignore

- common/changes/@itwin/grouping-mapping-widget/uyen-radio-button-selection_2023-10-09-23-19.json
- packages/itwin/grouping-mapping-widget/src/widget/components/ExtractionLogCustomFilter.tsx
Only allowed one selection for radio buttons instead of allowing multiple options selected.
> [G&M] Limited one selection for radio buttons

- .pipelines/pr.yaml
- .pipelines/templates/change-files-steps.yaml
- package.json
Fail CI pipeline if change files are missing
> Check change files in CI

- .pipelines/publish.yaml
Fix pipeline variable definition.
> Fix publish pipeline

- .pipelines/publish.yaml
- packages/itwin/property-grid/CHANGELOG.json
- packages/itwin/property-grid/CHANGELOG.md
Updated publish pipeline to fetch all history. This is required for beachball to look up commit that introduced change file.
> Fix changelog generation

- beachball.config.js
Disabled `breakdown-trees` publishing. Beachball tries to bump `tree-widget` peer dep and publish `breakdown-trees` to npm and fails. Chose to disable `breakdown-trees` publishing for a moment to avoid blocking publishing of other packages.
Fixed changelog generation to avoid git command failures when commit hash is not available.
> Disable breakdown-trees publishing

- .pipelines/publish.yaml
- apps/test-viewer/pnpm-lock.yaml
- change/@itwin-tree-widget-react-0c27369e-7f9e-45c9-bdcb-7c87ab609437.json
- change/@itwin-tree-widget-react-f668236d-535e-4729-b98f-7b57def39fec.json
- packages/itwin/tree-widget/CHANGELOG.json
- packages/itwin/tree-widget/CHANGELOG.md
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeEventHandler.ts
Merges https://github.com/iTwin/viewer-components-react/pull/750 changes into master.
> [Tree Widget]: Merge checkbox event handler fix into master

- change/@itwin-map-layers-d9e5289d-6536-4431-bfc4-fca342b66dcd.json
- packages/itwin/map-layers/src/ui/FeatureInfoUiItemsProvider.tsx
- packages/itwin/map-layers/src/ui/Interfaces.ts
Add support to show tech preview badge on new maplayer feature info tool/widget
> Maplayer Feature Info Tech Preview badge option

- change/@itwin-grouping-mapping-widget-0a534753-e511-4c0f-886f-4c5bc94a6d24.json
- packages/itwin/grouping-mapping-widget/src/components/Properties/GroupProperties/GroupPropertyAction.scss
> [G&M] Fixed an issue where the list would disappear if the list was too small

- change/@itwin-tree-widget-react-5e6a2cf8-befe-47a9-a941-2c9f59632e03.json
- packages/itwin/tree-widget/src/components/trees/category-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSourcesTree.tsx
- packages/itwin/tree-widget/src/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/test/TestUtils.tsx
Updates trees delivered with `@itwin/tree-widget-react` package to always react to data changes and auto update.
> [Tree Widget]: Auto update hierarchies

- change/@itwin-tree-widget-react-f98fd80f-13f5-4a51-a19a-24534da8b487.json
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/ModelsTreeDefinition.ts
- Change label filtering to filter only up to models (as in 2.x).
- Apply latest subject models hierarchy performance optimizations:
- https://github.com/iTwin/presentation/pull/598
- https://github.com/iTwin/presentation/pull/599
> Tree widget: Models tree definition optimizations

- change/@itwin-tree-widget-react-20184b30-f1cd-4b10-842f-330ab2bef8df.json
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/internal/ModelsTreeIdsCache.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/stateless/ModelsTreeDefinition.test.ts
Fixes https://github.com/iTwin/viewer-components-react/issues/881
> Tree widget: Fix childless Subject nodes being displayed in some cases

- change/@itwin-tree-widget-react-b93bc72f-2ab6-4c4a-91a7-ca54dd7e7bc0.json
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/internal/ModelsTreeIdsCache.ts
> Stateless models tree: Fix issue of model visibility taking into account extra categories

- change/@itwin-tree-widget-react-5b1cc91f-be89-4658-9e68-513db8deb9eb.json
- packages/itwin/tree-widget/src/components/trees/stateless/models-tree/internal/ModelsTreeIdsCache.ts
- packages/itwin/tree-widget/src/test/trees/stateless/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
> Stateless Models Tree: Fix issue of category node taking into account visibility of unrelated elements

- apps/test-viewer/.env.template
- apps/test-viewer/package.json
- apps/test-viewer/pnpm-lock.yaml
- apps/test-viewer/vite.config.mts
- packages/itwin/property-grid/playwright.config.ts
- packages/itwin/tree-widget/playwright.config.ts
Made hot reloading opt in because it might cause huge performance impact on first load depending on the system. Also added ability to enable `polling` for files watcher.
> Test-viewer: Make hot reloading opt in

- change/@itwin-ec3-widget-react-41176429-dd6c-44ad-8918-7872ecb4d9cd.json
- packages/itwin/ec3-widget/api/ec3-widget-react.api.md
- packages/itwin/ec3-widget/api/ec3-widget-react.exports.csv
- packages/itwin/ec3-widget/src/components/EC3/EC3Config.ts
- packages/itwin/ec3-widget/src/components/EC3Router.tsx
- packages/itwin/ec3-widget/src/components/EC3RouterProps.ts
- packages/itwin/ec3-widget/src/components/EC3Widget.tsx
- packages/itwin/ec3-widget/src/components/EC3WidgetProps.ts
- packages/itwin/ec3-widget/src/components/ExportModal.tsx
- packages/itwin/ec3-widget/src/components/TemplateProps.ts
- packages/itwin/ec3-widget/src/components/Templates.tsx
- packages/itwin/ec3-widget/src/ec3-widget-react.ts
- packages/itwin/ec3-widget/src/widget/EC3Widget.tsx
- Added success and failure callback props for EC3 export
- Moved all prop types to new files
> Added callback props for EC3 export

- change/@itwin-tree-widget-react-55b76f83-da47-44f9-8c45-2feb0fe894c4.json
- packages/itwin/tree-widget/src/components/TreeWidgetUiItemsProvider.tsx
- packages/itwin/tree-widget/src/components/trees/common/components/BaseTree.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/954.
> Tree widget: persist scroll position

- change/@itwin-ec3-widget-react-17a64684-49ac-4812-9bc9-4812e43ddccd.json
- change/@itwin-ec3-widget-react-e6914387-3229-468b-b44e-5ed0417b6703.json
- packages/itwin/ec3-widget/README.md
- packages/itwin/ec3-widget/public/locales/en/EC3Widget.json
- packages/itwin/ec3-widget/src/components/EC3/EC3Config.ts
- packages/itwin/ec3-widget/src/components/ExportModal.tsx
- packages/itwin/ec3-widget/src/components/Templates.tsx
- packages/itwin/ec3-widget/src/test/Templates.test.tsx
- Added template id in export callback for EC3
- Added missing localization strings in template
> Export callback changes for EC3

- apps/test-viewer/pnpm-lock.yaml
- change/@itwin-tree-widget-react-7ec6ef69-2516-4eb5-b5b2-c26c752ba02b.json
- packages/itwin/tree-widget/README.md
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/categories-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/components/trees/common/UseTelemetryContext.tsx
- packages/itwin/tree-widget/src/components/trees/common/components/Tree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/979.
> Tree Widget: Error reporting

- change/@itwin-tree-widget-react-eabea2bc-8ec7-45ef-85ee-0fc987744dc3.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/categories-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/components/trees/categories-tree/CategoriesTreeButtons.tsx
- packages/itwin/tree-widget/src/components/trees/categories-tree/CategoriesTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/categories-tree/UseCategoriesTree.tsx
- packages/itwin/tree-widget/src/components/trees/common/UseHierarchyVisibility.ts
- packages/itwin/tree-widget/src/components/trees/common/Utils.ts
- packages/itwin/tree-widget/src/components/trees/common/components/Tree.tsx
- packages/itwin/tree-widget/src/components/trees/common/components/TreeNodeRenderer.tsx
- packages/itwin/tree-widget/src/components/trees/common/components/TreeRenderer.tsx
- packages/itwin/tree-widget/src/components/trees/common/components/VisibilityTree.tsx
- packages/itwin/tree-widget/src/components/trees/common/components/VisibilityTreeRenderer.tsx
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSourcesTree.tsx
- packages/itwin/tree-widget/src/components/trees/external-sources-tree/ExternalSourcesTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/components/trees/imodel-content-tree/IModelContentTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeButtons.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeComponent.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/components/trees/models-tree/UseModelsTree.tsx
- packages/itwin/tree-widget/src/components/trees/models-tree/internal/ModelsTreeVisibilityHandler.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/VisibilityValidation.ts
Closes https://github.com/iTwin/viewer-components-react/issues/998
> Tree widget: Capture public API

- change/@itwin-tree-widget-react-93e170e8-e792-4e9b-a7fd-7f2e5014045a.json
- packages/itwin/tree-widget/src/components/trees/VisibilityTreeRenderer.tsx
Closes https://github.com/iTwin/viewer-components-react/issues/1015
Previously:
Fix:
> [Tree-widget]: fix visibility icon misalignment 

- apps/test-viewer/pnpm-lock.yaml
- change/@itwin-tree-widget-react-0f3fe6ae-4a80-46fe-9453-b50b194dbaad.json
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/common/UseHierarchyVisibility.ts
- packages/itwin/tree-widget/src/components/trees/common/Utils.ts
Added caching to class checker to speed up visibility status lookup.
Reduce main thread blocking when checking node visibility statuses.
> [tree-widget]: Reduce tree-widget UI blocking

- .pipelines/pr.yaml
- .pipelines/templates/validate-docs-steps.yaml
- change/@itwin-tree-widget-react-d0672cd1-e531-4cff-bd72-e6b7f1490dab.json
- lage.config.js
- packages/itwin/tree-widget/README.md
Fixes https://github.com/iTwin/viewer-components-react/issues/1114
> Docs: Check extractions

- change/@itwin-tree-widget-react-47712871-a634-4c85-9701-8c15d117abd3.json
- packages/itwin/tree-widget/package.json
- packages/itwin/tree-widget/pnpm-lock.yaml
- packages/itwin/tree-widget/src/components/trees/common/components/Tree.tsx
#closes https://github.com/iTwin/viewer-components-react/issues/1080
> On hierarchy load error logs error to console

- apps/test-viewer/src/components/ViewerOptions.tsx
Also filed a backlog item to update Viewer to allow supplying active selection scope without going through `Presentation.selection`: https://github.com/iTwin/viewer/issues/344
> Test viewer: Add selection scopes picker

- .github/workflows/e2e.yml
- .github/workflows/extract-api.yml
No point to do that at this point...
> Don't run e2e and extract-api pipelines on next branch

- change/@itwin-tree-widget-react-1d869975-3b59-430c-a4bd-5cac74855f57.json
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/imodel-content-tree/IModelContentTreeDefinition.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeDefinition.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/UseModelsTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
Closes https://github.com/iTwin/viewer-components-react/issues/951.
> Tree widget: Remove root node in models tree

- change/@itwin-tree-widget-react-82c4f50c-81e5-401e-94b0-16209a064319.json
- packages/itwin/tree-widget/src/test/trees/categories-tree/CategoriesTreeDefinition.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/internal/CategoriesTreeIdsCache.ts
> Fix definition container bug

- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTree.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/CategoriesTreeDefinition.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/categories-tree/UseCategoriesTree.tsx
> Add option to not show SubCategories in categories tree

- change/@itwin-tree-widget-react-28100080-1dc4-4358-9f4f-5a2278178039.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/e2e-tests/IModelContentTree.test.ts
- packages/itwin/tree-widget/src/e2e-tests/ModelsTree.test.ts
- packages/itwin/tree-widget/src/e2e-tests/TreeWidget.test.ts
- packages/itwin/tree-widget/src/e2e-tests/auth.ts
- packages/itwin/tree-widget/src/test/trees/Common.ts
- packages/itwin/tree-widget/src/test/trees/categories-tree/internal/CategoriesVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/categories-tree/internal/Utils.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/Utils.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/AlwaysAndNeverDrawnElementInfo.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeIdsCache.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/VisibilityChangeEventListener.test.ts
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/VisibilityValidation.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/ModelsTreeComponent.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/AlwaysAndNeverDrawnElementInfo.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/ModelsTreeVisibilityHandler.ts
closes [#1309](https://github.com/iTwin/viewer-components-react/issues/1309)
> Make merged nodes visibility work as expected

- apps/performance-tests/src/tree-widget/ClassificationsTree.test.ts
- change/@itwin-tree-widget-react-7b217755-afb3-490e-b520-e4aa73222148.json
- packages/itwin/tree-widget/api/tree-widget-react.api.md
- packages/itwin/tree-widget/src/test/Initialize.ts
- packages/itwin/tree-widget/src/test/trees/Common.ts
- packages/itwin/tree-widget/src/test/trees/classifications-tree/ClassificationsTreeDefinition.test.ts
- packages/itwin/tree-widget/src/test/trees/classifications-tree/ClassificationsTreeVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/test/trees/classifications-tree/HierarchyNodeUtils.ts
- packages/itwin/tree-widget/src/test/trees/classifications-tree/Utils.ts
- packages/itwin/tree-widget/src/test/trees/classifications-tree/VisibilityValidation.ts
- packages/itwin/tree-widget/src/test/trees/common/UseHierarchyVisibility.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/classifications-tree/ClassificationsTreeDefinition.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/classifications-tree/ClassificationsTreeIcon.tsx
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/classifications-tree/internal/ClassificationsTreeIdsCache.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/classifications-tree/internal/ClassificationsTreeNode.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/classifications-tree/internal/ClassificationsTreeVisibilityHandler.ts
Based on primary consumer's request...
> Tree widget: Remove categories from classifications tree

- change/@itwin-tree-widget-react-19ac682c-463b-4c62-b5cf-f36a1606bda6.json
- packages/itwin/tree-widget/src/test/trees/models-tree/internal/ModelsTreeVisibilityHandler.test.ts
- packages/itwin/tree-widget/src/tree-widget-react/components/trees/models-tree/internal/ModelsTreeIdsCache.ts
closes [1399](https://github.com/iTwin/viewer-components-react/issues/1399)
> [Tree widget]: Fix child element visibility problem in models tree
